### ISSUE TITLE
Clicking on tab opens in other window

### ISSUE THREAD

**Issue by Compro-Prasad** [ema2159/centaur-tabs#1]
## Reproduction steps
1. Open two files in the same project so that you have two tabs
2. `C-x 3` to split into two halves
3. Click on the other tab in other(currently inactive) window

## What I was expecting
Buffer opens in the other window

## Unexpected behaviour
Buffer opens in the same active window.

**Comment by ema2159** [comment]
That's some funny bug jaja. I intended this plugin to be used with the keyboard mostly, so I never encountered this bug, let me investigate it and if you find a solution before I do don't be afraid to submit a PR!
