### ISSUE TITLE
Alphabetical order

### ISSUE THREAD

**Issue by Ypot** [ema2159/centaur-tabs#101]
Is it possible to get alphabetical order in the tabs?

Thanks for your cozy package!

**Comment by ema2159** [comment]
I'm sure there's a way, but I haven't investigated it yet. It should be possible by using the seq-sort-by function.

**Comment by ema2159** [comment]
Done. Added a function previously created by @cburroughs (by the way, thanks man). It has a funky behaviour that has to be investigated though. When a new file is opened, the tab will always be added to the right of the current tab. That has to do with the behavior of the `find-file` command. I'll try to fix it in a near future.
