### ISSUE TITLE
`doom-monokai-pro` error: `Invalid face attribute :background nil`

### ISSUE THREAD

**Issue by laishulu** [ema2159/centaur-tabs#102]
see:

https://github.com/hlissner/emacs-doom-themes/issues/484

Also, through git blame, I read that that line of code comes from you.
And you are the author of `centaur-tabs`.
So, it should be a breathe for you to resolve the issue.

**Comment by ema2159** [comment]
Indeed! Thanks. Please tell me if that's ok!

**Comment by laishulu** [comment]
works, thanks!
