### ISSUE TITLE
centaur-tabs-plain-icons should respect inactive window state

### ISSUE THREAD

**Issue by ogdenwebb** [ema2159/centaur-tabs#103]
When I set `(setq centaur-tabs-gray-out-icons 'buffer)` and enable centaur-tabs-plain-icons, all my tabs will have the same color as foreground.

**Comment by ema2159** [comment]
Hello man! Long time no see. You're right! I'll try to look into it as soon as I can!

**Comment by ema2159** [comment]
Fixed in ab422dc!
