### ISSUE TITLE
Centaur-tabs-icon inherits border (:box property) from mode-line and mode-line-inactive faces

### ISSUE THREAD

**Issue by ogdenwebb** [ema2159/centaur-tabs#105]
Box property defined either in mode-line or mode-line-inactive face will cause this problem, because an icon from all-the-icons package displays border in this case. 

![tabs](https://user-images.githubusercontent.com/9018005/84524258-595bdb80-ace2-11ea-9188-d317f04b1c31.jpg)

I assume you should rely only on foreground and background properties instead of mode-line/mode-line-inactive face entirely.

https://github.com/ema2159/centaur-tabs/blob/ab422dc8381c319f8db417b476f09c8c23b4448f/centaur-tabs-elements.el#L191-L195

**Comment by ema2159** [comment]
You're right. Fixed! Please tell me if there is any other problem.
