### ISSUE TITLE
Configure single buffer-group for all tabs?

### ISSUE THREAD

**Issue by balaji-dutt** [ema2159/centaur-tabs#106]
Hello,

I recently came across this package via Hacker News and as a relatively new Emacs user, having tabs visible would be a nice bridge to moving away from Sublime Text etc.

However, I realize that by default centaur-tabs will place buffers into various buffer-groups ("Emacs" or "project group") and I find that it's a bit confusing for me to not have a consistent set of tabs visible. I've been trying to configure tab groups so that all buffer appear by default but the solution linked to in #48 does not seem to work.

Can you please offer some tips on how I could make all buffers appear by default in a single buffer group?

Here is my current centaur-tabs config:
```elisp
  (use-package centaur-tabs
    :demand
    :init
    (centaur-tabs-mode)
    :config
    (setq centaur-tabs-style "rounded")
    (setq centaur-tabs-set-icons t)
    (setq centaur-tabs-set-bar 'over)
    ;; (setq x-underline-at-descent-line t)
    (setq centaur-tabs-set-modified-marker t)
    (setq centaur-tabs-modified-marker "●")
    (defun centaur-tabs-hide-tab (x)
      "Disable tabs for certain buffer types"
      (let ((name (format "%s" x)))
        (or
         (window-dedicated-p (selected-window))
         (string-prefix-p "*epc" name)
         (string-prefix-p "*helm" name)
         (string-prefix-p "*Helm" name)
         (string-prefix-p "*which-key*" name)
         (string-prefix-p "*Compile-Log*" name)
         (string-prefix-p "*lsp" name)
         (and (string-prefix-p "magit" name)
              ))))
    ;; (centaur-tabs-group-by-projectile-project)
   :hook (
           ;; (dashboard-mode . centaur-tabs-local-mode)
           (treemacs-mode . centaur-tabs-local-mode)
           ;; (spacemacs-buffer-mode . centaur-tabs-local-mode)
           (term-mode . centaur-tabs-local-mode)
           (calendar-mode . centaur-tabs-local-mode)
           (helpful-mode . centaur-tabs-local-mode)
           (dired-mode . centaur-tabs-local-mode)
           (zone-mode . centaur-tabs-local-mode)
           ;; (helm-mode . centaur-tabs-local-mode)
           )
    :bind
    ("C-<prior>" . centaur-tabs-backward)
    ("C-<next>" . centaur-tabs-forward)
    (:map evil-normal-state-map
          ("g l" . centaur-tabs-forward)
          ("g h" . centaur-tabs-backward)
          ("SPC b n" . centaur-tabs-forward)
          ("SPC b p" . centaur-tabs-backward))
    )
  )
```

I'm using Emacs 26.3 with spacemacs on Windows 10.

**Comment by ema2159** [comment]
Hey! it's quite straight forward. You'd have to put the following function in your config
``` elisp
    (defun centaur-tabs-buffer-groups ()
      "`centaur-tabs-buffer-groups' control buffers' group rules.

Group centaur-tabs with mode if buffer is derived from `eshell-mode' `emacs-lisp-mode' `dired-mode' `org-mode' `magit-mode'.
All buffer name start with * will group to \"Emacs\".
Other buffer group by `centaur-tabs-get-group-name' with project name."
      (list
       "GROUP"))

````
You can put whatever you want instead of "GROUP". Please tell me if this works for you!

**Comment by balaji-dutt** [comment]
Hi @ema2159 thank you for the quick suggestion - that worked perfectly. Thank you!

I have a question around centaur-tabs and Org-mode windows. Specifically when I enter ```C-c-C-t``` to change an item's status in an org-mode file, I see the tabs appear in the org todo window:

![Org todo](https://i.imgur.com/e8XAIEb.png)

I have tried updating ``` (defun centaur-tabs-hide-tab (x)``` as follows but that does not seem to work:

```elisp
    (defun centaur-tabs-hide-tab (x)
      "Disable tabs for certain buffer types"
      (let ((name (format "%s" x)))
        (or
         (window-dedicated-p (selected-window))
         (string-prefix-p "*epc" name)
         (string-prefix-p "*helm" name)
         (string-prefix-p "*Helm" name)
         (string-prefix-p "*which-key*" name)
         (string-prefix-p "*Org todo*" name)
         (string-prefix-p "*Compile-Log*" name)
         (string-prefix-p "*lsp" name)
         (and (string-prefix-p "magit" name)
              ))))
```elisp

Can you tell me what I'm doing wrong?

**Comment by ema2159** [comment]
@balaji-dutt probably you just have to add a space before *Org todo like this `(string-prefix-p " *Org todo*" name)`.

Also, those ugly boxes around the icons should be solved now. They should be disappear with the next update.

**Comment by ema2159** [comment]
Also, all of the buffers that have a space before their name are hidden buffers so you might as well hide them all. You should try with `(string-prefix-p "  " name)` and if that doesn't work, try with `(string-prefix-p " *" name)`

**Comment by balaji-dutt** [comment]
@ema2159 Thanks!

> Also, those ugly boxes around the icons should be solved now. They should be disappear with the next update.

My ```all-the-icons``` integration in spacemacs is not very reliable at the moment as the icons do not appear on load. I have to either change my modeline completely or launch dired after which it seems to fix itself 😞

**Comment by ema2159** [comment]
It probably has ti do with something in the config. If you show me your config for `all-the-icons` I might be able to lend you a hand.

**Comment by balaji-dutt** [comment]
Thanks @ema2159! I'm using [this PR](https://github.com/syl20bnr/spacemacs/pull/13337/files) which is not yet merged to spacemacs. It does the following:

* Remove all-the-icons as a dependency from just company-mode
* Configures all-the-icons for dired, helm, ivy and company-mode.

As I mention with this setup, if I launch dired then the icons start to appear correctly.

**Comment by balaji-dutt** [comment]
Hah! I looked at the PR code again carefully and realized it was using  ```:defer t``` which explains the odd behavior. I changed it to ```:demand``` and that fixed the missing icons on startup! 😄 

The only glitch I can see now is the missing icons when I set ```(setq centaur-tabs-show-navigation-buttons t)```:

![navigation](https://i.imgur.com/wzIreWa.png)

**Comment by ema2159** [comment]
That is some font that needs to be installed, however I don't recall which! Tomorrow I'll look it up and get back to you!

**Comment by balaji-dutt** [comment]
It seems like centaur-tabs relies on the selected unicode characters for ```centaur-tabs-backward-tab-text``` (U+23F4) and ```centaur-tabs-forward-tab-text``` (U+23F5) to be available in the default-font-face. That was not working with the Powerline font I was using namely "Source Code Pro for Powerline".

I fixed this by looking through the list of characters in the Powerline font and replacing the unicode characters as follows:

```elisp
   (custom-set-variables
     '(centaur-tabs-backward-tab-text " ◄") ;;U+25C4
     '(centaur-tabs-forward-tab-text " ►")) ;;U+25BA
```
