### ISSUE TITLE
Error when byte-compiling;  centaur-tabs.el:45:1:Error: Cannot open load file: No such file or directory, powerline

### ISSUE THREAD

**Issue by thermopyle** [ema2159/centaur-tabs#11]
I updated to latest and get the above error.

**Comment by ema2159** [comment]
As I answered in the other issue, it's a dependency issue, you must download powerline (available on MELPA). When centaur-tabs gets in MELPA, those dependencies will be fixed automatically

**Comment by ema2159** [comment]
This has me thinking though... Could you go to centaur-tabs.el and remove the line that says `(require 'powerline)`, byte compile and tell me if it works (without having powerline installed)?

**Comment by thermopyle** [comment]
Will do, I'll try it tomorrow when I have time.

**Comment by thermopyle** [comment]
Byte compiling with the `(require 'powerline)` line commented out worked, executing the code did not (as expected). Lots of error messages referencing missing powerline resources. I added  a `(use-package powerline)` statement to the config part of the `(use-package centaur-tabs)` to install powerline together with centaur-tabs and then it worked to compile and run.

centaur-tabs is not activated correctly for me when I start opening buffers. I do not see any tabs until I use either of `centaur-tabs-backward` or `centaur-tabs-forward`, then the tabs appear. I tried adding a `:demand` statement to the `(use-package centaur-tabs)` statement, then tabs are visible from start. You can see my configuration below.

```
(use-package centaur-tabs
  :load-path "~/.emacs.d/src/centaur-tabs/"
  :demand
  :config
  (use-package powerline
    :ensure t)
  (setq centaur-tabs-set-modified-marker t)
  (setq centaur-tabs-set-bar t)
  (centaur-tabs-mode t)
  :bind
  ("C-<prior>" . centaur-tabs-backward)
  ("C-<next>" . centaur-tabs-forward))
```

**Comment by ema2159** [comment]
> Byte compiling with the (require 'powerline) line commented out worked, executing the code did not (as expected). 

Yes, I was expecting that, I just wanted to make sure just to make it a hard dependency.

> centaur-tabs is not activated correctly for me when I start opening buffers. I do not see any tabs until I use either of centaur-tabs-backward or centaur-tabs-forward, then the tabs appear. I tried adding a :demand statement to the (use-package centaur-tabs) statement, then tabs are visible from start. You can see my configuration below.

This is due to `use-package` deferring the package loading when there is a :bind keyword, it defers the package loading until one of the keybindings is pressed. Glad to know now it works properly!. May I close the issue now?

**Comment by thermopyle** [comment]
Yes, you can close it. Keep up the good work, this looks really promising.
I for one think Emacs needs good looking tabs!


Den tors 4 juli 2019 15:58Emmanuel Bustos Torres <notifications@github.com>
skrev:
