### ISSUE TITLE
[Help] Org-roam file names are too long for tabs

### ISSUE THREAD

**Issue by ivanddm** [ema2159/centaur-tabs#112]
I'm using org-roam and by default the the name of the files are assigned a string that starts with many digits, e.g `234223434092-some-notes.org`.

I would like to be able to either hide this kind of org files that start with such a big number (I tried to do it with some regex but failed, I'm new to Emacs...) or ideally to show the name of the file without the long number. The solution at the moment is that I disabled centaur-tabs in org-mode, which is not ideal.

Thanks in advance.

**Comment by ema2159** [comment]
Hi man! I'm really embarrassed. I've been quite absent given I've been really busy with a lot of personal matters and this pandemic has made everything harder. 

The thing is, is the "`some-notes`" part of the name consistent? Like, is it always the same? If yes, then you have two possible solutions. One is to completely hide the long digits buffer, adding them to the buffer hiding function. Just follow the instructions in the **Prevent access to specified buffers in the README** which I just updated with better instructions, changing `*mybuf` for `*some-notes.org`. The other option would be to group them in a different tab group. If the latter is the option that you want to chose, let me know to give you further instructions.

**Comment by ivanddm** [comment]
Hi! sure, no worries at all!

No, the "`some-notes`" part will be different for every file (similar to the notes title).

Thanks a lot in any case if this is not possible to accomplish.

**Comment by ema2159** [comment]
Could you show me some screenshots?

**Comment by Riyyi** [comment]
@ema2159 Org-roam has a find file function, if you type in something that doesnt exist it create a new .org file named
```20200812053042-<your_typed_thing>.org``` (without the <>) where spaces and dashes from the input are replaced with _. Then it starts an org capture on that new file so you also get ```CAPTURE-20200812053042-<your_typed_thing>.org```.
I think using the buffer-hide function would work as the pattern is specific enough  ```(CAPTURE-)?[0-9]{14}-\w+\.org```.

**Comment by ema2159** [comment]
@Riyyi yeah! I was thinking of using a regex like that! But I'm not sure if string-prefix-p works with regexes or just with wildcards. If it woks with regexes then we could use a pattern like that, if not, I think we'd have to use another function for the matching but it should definitely be possible.

**Comment by Riyyi** [comment]
@ema2159 
It does not, you'd have to use `string-match-p`.
@ivanddm 
I have a working example, add this to the `or` statement in your `centaur-tabs-hide-tab` function:
`(string-match-p "\\(CAPTURE-\\)?[0-9]\\{14\\}-[0-9a-zA-Z_]+\\.org" name)`

**Comment by ema2159** [comment]
Also, I'm noting that the name of the file starts with information about the current date (at least the first 8 digits, the rest I'm not sure what they are). I tried your regex and for some reason, it didn't work. Here's my take though:
``` elisp
(string-match-p (concat "\\(CAPTURE-\\)?" (format-time-string "%Y%m%d") ".*-.*\\.org") name)
```
It will match every string starting with the optional matching of the "CAPTURE-" string, followed by the date, then it matches the dash and the .org extension.  I think either one should do the job.

**Comment by Riyyi** [comment]
I actually prefer your version, so it only hides newly created files. The other digits were the timestamp (yes I was up at 5:30 lol). The regex probably didn't work because the dash is directly after the timestamp. I added this to my config.org.
```emacs-lisp
(string-match-p (concat "\\(CAPTURE-\\)?" (format-time-string "%Y%m%d%H%M%S") "-.*\\.org") name)
```
Not sure about the CAPTURE issue.

**Comment by ema2159** [comment]
Is your CAPTURE part working? that's very odd. I wouldn't add the %M%S part to the timestamp, it would be too granular so the buffers would appear from one second to another. Also, you're an early bird like me haha, being an early bird rocks.

**Comment by Riyyi** [comment]
Yes, both of the buffers get hidden for me (with your version as well). I like it to be this granular although I realize that's not what OP asked for.

**Comment by ema2159** [comment]
Awesome. Then, @ivanddm, could you try adding the following to your config:

```elisp
(defun centaur-tabs-hide-tab (x)
  "Do no to show buffer X in tabs."
  (let ((name (format "%s" x)))
    (or
     ;; Current window is not dedicated window.
     (window-dedicated-p (selected-window))

     ;; Buffer name not match below blacklist.
     (string-prefix-p "*epc" name)
     (string-prefix-p "*helm" name)
     (string-prefix-p "*Helm" name)
     (string-prefix-p "*Compile-Log*" name)
     (string-prefix-p "*lsp" name)
     (string-prefix-p "*company" name)
     (string-prefix-p "*Flycheck" name)
     (string-prefix-p "*tramp" name)
     (string-prefix-p " *Mini" name)
     (string-prefix-p "*help" name)
     (string-prefix-p "*straight" name)
     (string-prefix-p " *temp" name)
     (string-prefix-p "*Help" name)
     (string-match-p (concat "\\(CAPTURE-\\)?" (format-time-string "%Y%m%d") ".*-.*\\.org") name)

     ;; Is not magit buffer.
     (and (string-prefix-p "magit" name)
	  (not (file-name-extension name)))
     )))
```

**Comment by ivanddm** [comment]
Hey guys @Riyyi and @ema2159, thanks a lot for the ideas. So basically the tab name of a normal `org-roam` file looks like this:

<img width="1106" alt="Screen Shot 2020-08-12 at 8 34 01 PM" src="https://user-images.githubusercontent.com/20104703/90048000-84ab7880-dcdb-11ea-8348-0fa8d03dc10a.png">

Therefore `(string-match-p (concat "\\(CAPTURE-\\)?" (format-time-string "%Y%m%d") ".*-.*\\.org") name)` was not working for me, and neither was `(string-match-p (concat (format-time-string "%Y%m%d") ".*-.*\\.org") name)`.

However, I got it working based on @Riyyi's initial suggestion: 

```elisp
(string-match-p (concat "[0-9]\\{14\\}" ".*-.*\\.org") name)`. 
```

This is working for me and it is hiding only the `org-roam` tabs and not other normal `org` tabs, which is what I wanted.

Thanks a lot again. Feel free to close this issue.

**Comment by ema2159** [comment]
Perfect!
