### ISSUE TITLE
The "centaur-tabs-extract-window-to-new-frame" function overrides Auctex keybinding

### ISSUE THREAD

**Issue by satigik** [ema2159/centaur-tabs#117]
Hello, I love centaur-tabs, never had a problem with it that I could not solve --until today. :(

The keybinding defined for the function "centaur-tabs-extract-window-to-new-frame" is interfering with Auctex. When editing LaTex with Auctex mode, C-c C-e is the keybinding for entering a new environment in the text. So today, it was a hassle to find out why instead of creating a new environment in my LaTex file, C-c C-e was opening my current buffer in a new frame. I had some idea that such behavior could be linked to today's centaur-tabs update because Auctex was working fine until yesterday. But I didn't find anything in the latest changelogs. 
I don't see any option for deactivating this behavior in centaur-tabs settings, so I will try to redefine the keybinding in the configuration file, but I am not sure if it will work. I can turn centaur-tabs-mode off, of course (it works, I tested), but I really love using centaur-tabs.

Though this is not an actual code issue, I decided to write about it here so other people won't have to spend the time I spent to find the source of this problem. I also would like to ask the developers to take care when they define automatic and hard to find keybindings that might override major modes' bidings. Is Auctex that obscure? Anyway, I know keybindings are not infinite, so I ask you to, please, make this kind of change clear in the README.org. 

If I am doing something wrong, or if there is a quick fix for this, please, let me know. I am not a lisp programmer. 

Thanks!

**Comment by ema2159** [comment]
Hi! I'm sorry, you're right. Those key bindings are hard coded, which is a bad practice so I will disable them by default. I'll try to do so soon and get back at you!

**Comment by satigik** [comment]
Thank you very much! :)

**Comment by ema2159** [comment]
@satigik done!
@alvarogonzalezsotillo just be aware that for enabling the keybindings you now have to follow the instructions in the new _Key bindings_ section

**Comment by satigik** [comment]
It's working! Thanks again! =D
