### ISSUE TITLE
Need to run all-the-icons-install-fonts every time Emacs loads for icons

### ISSUE THREAD

**Issue by Rimbo** [ema2159/centaur-tabs#118]
So maybe there's something wonky in my .emacs, but I've noticed that on both Emacs 26 and 27.1, on both macos emacs and vanilla emacs (precompiled package OR built myself), that in order for icons to show up, I have to run `all-the-icons-install-fonts` in my .emacs. For some reason, whatever that command does doesn't stick between sessions.

Could be an issue with that package, or just me being dumb. Any ideas why? And let me know what I should copy from *Messages* or otherwise to help you diagnose.

.emacs: 
```(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
  ;; and `package-pinned-packages`. Most users will not need or want to do this.
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  )

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["#ffffff" "#c82829" "#718c00" "#eab700" "#4271ae" "#8959a8" "#4271ae" "#4d4d4c"])
 '(centaur-tabs-mode t nil (centaur-tabs))
 '(centaur-tabs-set-icons t)
 '(custom-enabled-themes (quote (base16-tomorrow)))
 '(custom-safe-themes
   (quote
    ("2d035eb93f92384d11f18ed00930e5cc9964281915689fa035719cab71766a15" "cea3ec09c821b7eaf235882e6555c3ffa2fd23de92459751e18f26ad035d2142" "3860a842e0bf585df9e5785e06d600a86e8b605e5cc0b74320dfe667bcbe816c" default)))
 '(default-frame-alist (quote ((width . 132) (height . 50))))
 '(org-fontify-whole-heading-line t)
 '(org-hide-emphasis-markers t)
 '(org-hide-leading-stars t)
 '(package-selected-packages
   (quote
    (poet-theme treemacs-magit base16-theme color-theme-sanityinc-tomorrow treemacs-all-the-icons lsp-mode lsp-treemacs lsp-ui vterm emojify grandshell-theme all-the-icons all-the-icons-dired all-the-icons-gnus all-the-icons-ibuffer all-the-icons-ivy-rich centaur-tabs treemacs treemacs-icons-dired)))
 '(tool-bar-mode nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "Source Code Pro" :foundry "ADBE" :slant normal :weight normal :height 196 :width normal)))))

;; get mah fontses
;; (all-the-icons-install-fonts t)

;; go treemacs
(treemacs)
```

Naturally, as soon as I run `(all-the-icons-install-fonts t)` everything looks fine.

**Comment by ema2159** [comment]
Hi Rimbo! That's related to `all-the-icons.el` and how it installs its fonts. Could you please check in your systems if the fonts are installed properly? Also, you usually just have to run `all-the-icons-install-fonts` once, so it's better to do so interactively with M-x. Maybe it is that you're from your config every time you open Emacs!

Let me know how this goes for you.

**Comment by Rimbo** [comment]
GAAAAAAAAHHHH...

You know what was missing from my .emacs?

`(require 'all-the-icons)`

Seriously. That was it. Now it works. What the hell. 

I was messed up because `(all-the-icons-install-fonts t)` worked just fine. But then I found I couldn't run e.g. `(all-the-icons-insert-icons-for 'alltheicon)`, but I *could* run `(all-the-icons-insert 'alltheicon)`. And then when I ran the latter, the former suddenly became available... which is pretty much the behavior I was seeing.

OK, no worries. My bad. Seems that installing a package should do that for you, though... :|

**Comment by ema2159** [comment]
Don't worry. That happens more often than one may think haha. The reason why `centaur-tabs` doesn't do that installation for you is because `all-the-icons` is a soft dependency, so it's optional.

**Comment by Rimbo** [comment]
Yeah, I don't mind the soft dependency; I'm more upset that simply installing all-the-icons doesn't trigger that `(require ...)`. Like every other package does. 

TO be clear, `(all-the-icons-install-fonts t)` had done everything right; the reason I was having to re-run it was that running it was *also* triggering that `(require ...)` somewhere along the line.

So perhaps this is a bug with THAT thing. 🤷

**Comment by ema2159** [comment]
No! It isn't a bug. Emacs won't load a package unless it's asked to do so. Although I would highly recommend to take a look at `use-package`. It makes configuring and maintaining Emacs much much easier, and although it has a little bit of a learning curve (not that much really), it is really worth it.

**Comment by Rimbo** [comment]
That's odd, because it looked like all my *other* `(require ...)` commands didn't need to be run once I started using the Emacs Package. lsp-mode, treemacs, centaur-tabs... they just work once I install them.

Ah... perhaps Emacs is just being lazy about doing that, since it *does* work if I call any other available `all-the-icons-*` function, and with e.g. treemacs, centaur-tabs, lsp-mode, I have either explicit declarations or hooks that run those functions, but no such function with all-the-icons (other than the implicit invocation from centaur-tabs, which is just fine with the function not yet being available), eh?
