### ISSUE TITLE
previous and next arrow not showing

### ISSUE THREAD

**Issue by LanceMeister** [ema2159/centaur-tabs#125]
The previous and next arrows are missing...
![Screenshot 2020-09-25 at 15 20 20](https://user-images.githubusercontent.com/20726209/94271975-b05c8800-ff42-11ea-90e1-cdbe33bd991e.png)

how do I fix this? it would be visually better with the arrows 
(setq centaur-tabs-set-bar 'under) doesn't do anything ... may be deprecated

**Comment by ema2159** [comment]
Hi! The first issue is most likely due to some fonts missing. You can either install the Source Code Pro or the Google Noto Sans Symbols2 font and that should solve the issue
With regards to the second issue, it is not deprecated, you just have to call it before you do call `(centaur-tabs-mode)` in your config.

**Comment by LanceMeister** [comment]
Hi thank you so much for your reply. I will try to implement your instructions.

**Comment by LanceMeister** [comment]
![image](https://user-images.githubusercontent.com/20726209/94774287-dad49800-03bd-11eb-921f-4294e3342e69.jpeg) I looked and the code is before the centaur-tabs-mode. The funny thing is over and under do not work with this configuration but left and right do.

**Comment by LanceMeister** [comment]
Maybe it's not compatible with my Dracula theme

**Comment by ema2159** [comment]
If it is the regular Dracula theme then no, centaur-tabs isn't supported there. You could open an issue requesting such support in their repo. You could also try [Doom Themes'](https://github.com/hlissner/emacs-doom-themes) version of Dracula which is completely supported (alongside a good amount of well-curated, well-maintained themes).

Regarding the drop-down M-x, I use [Ivy posframe](https://github.com/tumashu/ivy-posframe) do so!

**Comment by ema2159** [comment]
Did you figure it out? If you did, please feel free to close this issue!
