### ISSUE TITLE
Tabs Hide the spell check Choices

### ISSUE THREAD

**Issue by rnwolf** [ema2159/centaur-tabs#128]
I am using DOOM, and when I use the spell checker, the word choices are hidden in or by the Tabs.

What I see without centaur-tabs. I can select which word to use at the top of the screen.

![Screenshot 2020-10-14 222556](https://user-images.githubusercontent.com/117415/96048471-9261b380-0e6e-11eb-9d03-bbdd6868bb34.png)

What I see when centaur-tabs is enabled.  I can't see the spellcheck choices.

![Screenshot 2020-10-14 223907](https://user-images.githubusercontent.com/117415/96048450-8bd33c00-0e6e-11eb-8154-b8aac698caca.png)

The picture above was taken with hook configuration in an attempt to disable when in flyspell-mode.

![Screenshot 2020-10-14 222933](https://user-images.githubusercontent.com/117415/96048458-8f66c300-0e6e-11eb-832d-92996b8c8eb3.png)

This picture above was taken without any hook to disable the tabs.

Here is the relevant section from config files:

config.el
```
(use-package! centaur-tabs
   :config
     (setq centaur-tabs-set-bar 'over
           centaur-tabs-set-icons t
           centaur-tabs-gray-out-icons 'buffer
           centaur-tabs-height 24
           centaur-tabs-set-modified-marker t
           centaur-tabs-modified-marker "•")
     (centaur-tabs-mode t)
  :hook
  (flyspell-mode . centaur-tabs-local-mode))


```
 
packages.el
```
(package! centaur-tabs) ;; CAUSES SPELL CHECKER INTERFACE TO BREAK.
```

**Comment by ema2159** [comment]
Which Emacs version is your Doom Emacs using?

**Comment by rnwolf** [comment]
Doom v2.0.9 (HEAD -> develop, origin/develop, origin/HEAD aedb7742d 2020-10-13 01:03:51 -0400)
GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-08-21

**Comment by ema2159** [comment]
There's a problem with that, and it is that it seems that the spell checker is using the tab-line space which it shouldn't. If that's the case, there's not much that can be done since both centaur-tabs and the spell checker will be constantly conflicting for that space.

Coud you try and see what happens if instead of centaur-tabs you used vanilla Emacs tabs? `(tab-line-mode)`

**Comment by rnwolf** [comment]
That seems to work fine.  Thanks for the tip.
