### ISSUE TITLE
Question: How to change the close button color?

### ISSUE THREAD

**Issue by ig-perez** [ema2159/centaur-tabs#135]
Hi, first of all thanks for creating this awesome package. I'm using a custom close button but the character has the same color as the tab name. I'd like to change its color so it highlights over the rest of the characters in the tabs.

Is it possible? How?

Thanks!

**Comment by black7375** [comment]
This screenshot is `M-x` than execute `list-faces-display`.
You can change color for `centaur-tabs-close-mouse-face`, `centaur-tabs-close-selected`. `centaur-tabs-close-unselected`.
![list-faces-display](https://user-images.githubusercontent.com/25581533/99143307-4fa12000-2654-11eb-8a6f-0639d7338864.png)

**Comment by ig-perez** [comment]
> This screenshot is `M-x` than execute `list-faces-display`.
> You can change color for `centaur-tabs-close-mouse-face`, `centaur-tabs-close-selected`. `centaur-tabs-close-unselected`.
> ![list-faces-display](https://user-images.githubusercontent.com/25581533/99143307-4fa12000-2654-11eb-8a6f-0639d7338864.png)

Thanks! I'll take a look

**Comment by ig-perez** [comment]
I finally used `set-face-foreground` in my init files:

```lisp
(set-face-foreground 'centaur-tabs-close-selected "#color1")
(set-face-foreground 'centaur-tabs-close-mouse-face "#color2")
```
Thanks!
