### ISSUE TITLE
Can I change the color when hovering over a tab?

### ISSUE THREAD

**Issue by black7375** [ema2159/centaur-tabs#136]
I'm happy to find a very cool project during the refactoring process.
I salute you for your work.

Currently, I know it is only possible with the close button. (`centaur-tabs-close-mouse-face`)
In emacs27's `tab-line-mode`, you can change the color when hovering under the name ``tab-line-highlight``.
![emacs27-tab-line](https://user-images.githubusercontent.com/25581533/99141527-195ba480-2644-11eb-970b-16ae870c687a.png)

+
The emacs27 has a tab addition button.
![emacs27-new-button](https://user-images.githubusercontent.com/25581533/99141762-5f196c80-2646-11eb-8b21-6aec0e568b46.png)

It's a role to pick a buffer to see with the tab, but I use it to create a new tab and it's very similar to a normal editor.
``` emacs lisp
;; Create empty buffer
(defun new-empty-buffer ()
  "Open a New empty buffer."
  (interactive)
  (let ((buf (generate-new-buffer "New empty")))
    (switch-to-buffer buf)
    (funcall (and initial-major-mode))
    (setq buffer-offer-save t)))

;; Redefine
(defun tab-line-new-tab (&optional e)
  (interactive "e")
  (new-empty-buffer))
```
![emacs27-new-empty](https://user-images.githubusercontent.com/25581533/99141983-8709cf80-2648-11eb-93d9-56e0b29d8d59.png)

As a part of `centaur-tabs-show-navigation-buttons`, I hope it will be reflected in future work.

**Comment by ema2159** [comment]
I think I can easily add this functionality. I do remember that when I was a tabbar-ruler user this functionality was present, and if I'm not wrong it should be easy to add.

**Comment by ema2159** [comment]
Sorry for the year-long delay! It was indeed very easy to implement! You can now customize the `centaur-tabs-name-mouse-face` as you see fit. I defaults to nil.

**Comment by black7375** [comment]
ㅒh very good news :+1: 
It's the best emacs tabbar package.
