### ISSUE TITLE
evil-scroll-down error when centaur-tabs-mode active

### ISSUE THREAD

**Issue by lccambiaghi** [ema2159/centaur-tabs#148]
As title. When I hit `C-d` I get an error in the echo area.

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  evil-scroll-down(nil)
  funcall-interactively(evil-scroll-down nil)
  command-execute(evil-scroll-down)
```

**Comment by lccambiaghi** [comment]
By debugging the `evil-scroll-down` function I managed to restrict the problem to the following line:
```
(goto-char (posn-point (posn-at-x-y 0 0)))
```
When I have centaur-tabs-mode enabled `(posn-point (posn-at-x-y 0 0))` returns nil. If I disable it, it correctly returns the position.

**Comment by sgleizes** [comment]
I don't have quite the same behavior, but I remember patching `evil-posn-x-y` to take the tab bar height into account.
See https://github.com/emacs-evil/evil/issues/1322 and the related PR.

**Comment by nebhrajani-a** [comment]
This isn't an issue with `centaur-tabs`: `evil` needs to take into account the height of the tab-bar. See [the fix](https://github.com/emacs-evil/evil/pull/1323) at `evil`. For some reason, this still hasn't been merged by `evil`'s maintainers.
