### ISSUE TITLE
Question: Setting a maximum width for tabs?

### ISSUE THREAD

**Issue by aclarknexient** [ema2159/centaur-tabs#149]
Is it possible to automatically truncate the tab titles? In other words, define a maximum width for tabs.

In other words, instead of:

`[foo.org][a_very_long_descriptive_filename.org][bar.org]`

It would display this if max-width was set to 8:

`[foo.org][a_very_d...][bar.org]`

Or if it was set to 16:

`[foo.org][a_very_descripti...][bar.org]`

Thank you!

**Comment by ema2159** [comment]
Hi! It would be through setting the `centaur-tabs-label-fixed-length` variable in your config (i.e. ``(setq centaur-tabs-label-fixed-length 10)`.

**Comment by ema2159** [comment]
Now I properly documented the custom variable in the README.
