### ISSUE TITLE
Quick question: How does centaur-tabs group projects?

### ISSUE THREAD

**Issue by ianpan870102** [ema2159/centaur-tabs#15]
I am not using Projectile, however centaur-tabs still groups my projects (which isn't a bad thing!) I'm asking only to understand its mechanism and behavior.

**Comment by ema2159** [comment]
Black magic JAJA. I'm not quite sure, because this is a fork from `awesome-tab`, and this is a feature that the previous author had implemented and I've never had to change it so I haven't checked any details in that function. I'll check the code and then give you a proper answer!

**Comment by ema2159** [comment]
It's pretty simple. It seems Emacs has an own, basic set of project management functions. In this case, it uses the `project-current` function to get the name of the current project probably checking for a .git directory upwards in the directory hierarchy.
