### ISSUE TITLE
hard coding ido-completing-read precludes use of other completing mechanisms

### ISSUE THREAD

**Issue by rileyrg** [ema2159/centaur-tabs#155]
Some completion mechanisms use core completing-read. Would be nice to revert to completing read in order to facilitate, for example, [selectrum](https://github.com/raxod502/selectrum).

**Comment by rileyrg** [comment]
#154

**Comment by rileyrg** [comment]
#154

**Comment by ema2159** [comment]
Great catch! Thank you for taking the time to submit a PR also! Will merge it soon

**Comment by rileyrg** [comment]
Thank you so much. My first. I did debate whether to make the completing func a function choice rather than just ido or completing read but I think it's a good balance.
