### ISSUE TITLE
Disable centaur-tabs in Calc buffer?

### ISSUE THREAD

**Issue by benthamite** [ema2159/centaur-tabs#158]
The [Calc](https://www.gnu.org/software/emacs/manual/html_mono/calc.html) buffer is very small, and having centaur-tabs enabled in that mode becomes very obtrusive. I tried to disable it following the instructions [here](https://github.com/ema2159/centaur-tabs#disable-centaur-tabs-in-selected-buffers) but I wasn't able to make it work. Specifically, these are the hooks I tried (I'm not sure which of the two is the appropriate one, but neither of them disabled centaur-tabs):

`(add-hook 'calc-mode-hook 'centaur-tabs-local-mode)`
`(add-hook 'calc-buffer 'centaur-tabs-local-mode)`

Any help would be appreciated.

**Comment by lucasgruss** [comment]
Would the following work for you ? 
```
(add-hook 'calc-mode-hook #'centaur-tabs-local-mode)
(add-hook 'calc-trail-mode-hook #'centaur-tabs-local-mode)
```
Be sure to kill the calc buffer whenever you try to change the hooks, as running `M-x calc` with an existing calc buffer will only bring it up, but the hooks won't be run. Pressing "q" only buries the buffer and does not kill it.

**Comment by benthamite** [comment]
That worked. Thank you!
