### ISSUE TITLE
Set-bar 'over needs multiple init file reloads

### ISSUE THREAD

**Issue by ianpan870102** [ema2159/centaur-tabs#16]
Hi @ema2159 thanks for adding the over-bar feature so quickly! It really resembles the firefox theme and it's looking super cool.

However, I noticed that I had to load the config file more than once to get the over-bar working, whereas if I set it to the left it needs only one reload. Perhaps it's the way I'm organizing my init file, or could it be an ordering issue in your latest commit? Here's my snippet:

```
  (use-package centaur-tabs
    :demand
    :config
    (centaur-tabs-mode)
    (setq centaur-tabs-set-modified-marker t
          centaur-tabs-modified-marker "●"
          centaur-tabs-cycle-scope 'tabs
          centaur-tabs-height 32
          centaur-tabs-set-bar 'over))
```

**Comment by ianpan870102** [comment]
Indeed, it seems to be an ordering issue, because it will work if I do
```
:init (setq centaur-tabs-set-bar 'over)
```
effectively setting the variable before the package is loaded.

Please feel free to close this if you find this workaround good enough.

**Comment by ema2159** [comment]
It has to be loaded before the (centaur-tabs-mode) because that's the function that loads the overline, although I think it's not the proper way to do it. I'll see if I can load it another way

**Comment by ema2159** [comment]
I'll close this for now as there's a "simple" solution but I certainly will improve it!
