### ISSUE TITLE
Customize navigation-buttons text

### ISSUE THREAD

**Issue by Bobbbay** [ema2159/centaur-tabs#168]
Hey! Great project. One of the most glaring issues that I have is that my navigation buttons end up looking like this:

![image](https://user-images.githubusercontent.com/49123594/146288923-9ab7ab17-0a43-468f-b31e-c268753efcc6.png)

(note the unrecognized font symbols for left and right)

Which is obviously not what I want :). I would love if we could change this text, as well as the down arrow's, to a custom string, in case of cases like these.

Font: Fira Code
Version: 27.1

**Comment by nebhrajani-a** [comment]
Do you have `all-the-icons` installed correctly? Are the fonts for `all-the-icons` installed?

**Comment by ema2159** [comment]
I think this may be the same issue as #80. The solution was to install Google Noto Sans Symbols2. In general, those weird characters indicate that there are fonts missing, so you should try that.

**Comment by Bobbbay** [comment]
> I think this may be the same issue as #80. The solution was to install Google Noto Sans Symbols2. In general, those weird characters indicate that there are fonts missing, so you should try that.

Thank you, installing Noto Sans worked!
