### ISSUE TITLE
Tabs are unwantingly automatically reordered

### ISSUE THREAD

**Issue by ianpan870102** [ema2159/centaur-tabs#17]
If I switch focus of buffers (either by `C-x b` or clicking on the tab bar), the order of the tab bars will unpredictably scramble, especially when the switched-from tab and the switched-to tab aren't next to each other.

To reproduce the problem, open four tabs in the same grouping, say:

`| index.html | app.js | sw1.jsx | sw2.jsx |`

and I have my current buffer focus on the first tab (`index.html`). As soon as I click the last tab (`sw2.jsx`), the order of the tabs becomes:

`| app.js | sw1.jsx | index.html | sw2.jsx |`

Then I click on the second tab (`sw1.jsx`) and the order becomes:

`| app.js | sw1.jsx | sw2.jsx | index.html |`

I'm not sure what's causing this issue, but I'm sure most users would expect the four tabs to stay in their same position, no matter the change of focus.

P.s. I'm suspecting this is the behavior of Emacs ordering the buffers internally since Centaur-Tabs does not keep track of the buffers with its own index list?

Thanks for your time, let me know if you need more details!

**Comment by ema2159** [comment]
I'm aware of this one, It's something that the previous author did so I'll investigate about it when I have some time! Thanks for liking my package so much!

**Comment by ema2159** [comment]
By the way, you have some theme packages am I right? Would you theme centaur-tabs with the following guidelines?

- The selected tab background should blend with the editing buffer
- If you use solaire-mode (which you should, it's goddamn awesome!), the unselected tab's background should match the solaire-default face (it should match the Treemacs/Neotree background for example)
- The modified marker, left/over bar and doom-modeline's bar should match
- The selected/unselected modified foreground should match

**Comment by ianpan870102** [comment]
> Would you theme centaur-tabs with the following guidelines?

I have thought about it indeed! But then I realized wouldn't it had been more easier/portable if Centaur Tabs inherit whatever the current theme's background color is? This way, all the theme authors don't have to specifically add a Centaur Tabs section in their code. But maybe there's something stopping this that I'm not considering, so please correct me if I'm wrong.

> I'll investigate about it when I have some time!

Sure! Honestly there isn't something major to complain about this package. It really is a nice piece of code. Thank you for doing this.

> Thanks for liking my package so much

Absolutely!

**Comment by ema2159** [comment]
> I have thought about it indeed! But then I realized wouldn't it had been more easier/portable if Centaur Tabs inherit whatever the current theme's background color is? This way, all the theme authors don't have to specifically add a Centaur Tabs section in their code. But maybe there's something stopping this that I'm not considering, so please correct me if I'm wrong.

This is kinda complicated because there's several faces to customize, and that need to explicitly be set. Also, it's better to have a custom customization for each theme because it makes the plugin integrate  nicely with the theme and it really improves the aesthetics. You could check in the Kaolin themes of Doom themes config and theme centaur-tabs in your themes following those configs as example then tell me and I'll add your themes to the known supported themes section!

**Comment by ianpan870102** [comment]
Gotcha, I'm in the process of cleaning up my theme code and **I will add support for Centaur Tabs** to both my **Wilmersdorf** Theme and **Tron Legacy** Theme! In the meanwhile, I have submitted a pull request for the **Zenburn** theme to also have Centaur Tabs support, hopefully it will be merged into master soon. You can track it here: https://github.com/bbatsov/zenburn-emacs/pull/330

**Also, I'd like to know what controls the face attribute background color of the free space on the right to the tabs (assuming that tabs didn't fill up the space)? It's mostly just dark-grey to me.**

P.s. see screenshot: the unused tab space on the right of `init.el` tab.

<img width="835" alt="Screenshot 2019-07-13 at 02 17 39" src="https://user-images.githubusercontent.com/36686900/61149768-81601f00-a514-11e9-8f95-8279dc6837b8.png">

**Comment by ema2159** [comment]
Nice! Zenburn is a very used theme! Thanks!.

What controls the the free space is the headerline-face, but I'd rather don't touch it because some themes use that face for other faces. Instead I use the (centaur-tabs-match-headline) function so the unselected tabs blend with the free space

**Comment by ianpan870102** [comment]
> I'd rather don't touch it because some themes use that face for other faces.

Makes sense, I'll leave it so.

> Zenburn is a very used theme

Indeed, being the **#1 most downloaded** theme on the Emacs Theme website (https://emacsthemes.com/popular/index.html), I hope my pull request could help more people reach out to your package.

**Comment by ema2159** [comment]
>I hope my pull request could help more people reach out to your package

That would be really nice!
By the way, I haven't thanked you enough Ian! Thanks to you my package has got a lot of attention these days! I'm really really grateful :D!

**Comment by ianpan870102** [comment]
> My package has got a lot of attention these days!

No problem! It's great to know someone that shares the same aesthetic taste and/or passion in Emacs. FTR I'd really want emacs to not just be the most functional and powerful editor, but also be as nice looking as modern apps!

**Comment by ema2159** [comment]
> > My package has got a lot of attention these days!
> 
> No problem! It's great to know someone that shares the same aesthetic taste and/or passion in Emacs. FTR I'd really want emacs to not just be the most functional and powerful editor, but also be as nice looking as modern apps!

Yeah, people really ignore the importance of a good UI, and I simply don't understand why they think that functionality an appearance are exclusive to one another.

By the way, i fixed the problem of this issue! I just removed the buffer ordering function completely, I found that it was completely unnecessary. I don't think it will break anything but if it does just let me know!

**Comment by jixiuf** [comment]
the buffer ordering function is trying to make the recent visited buffer stay  together .
after that you can use `centaur-tabs-forward` or `centaur-tabs-backward` to switching between them .

**Comment by ema2159** [comment]
@jixiuf yes, that's what I thought but, is it really needed? Do you consider its somehow needed or do you use it? The other option was to keep it and then just disable ot through the variable that calls the reordering function but I'm jot quite sure, what do you think?

**Comment by jixiuf** [comment]
I am using it .
I think you can disable the reordering by default 
```
(defvar centaur-tabs-adjust-buffer-order-function 'nil)
(when  centaur-tabs-adjust-buffer-order-function
  (add-hook 'post-command-hook centaur-tabs-adjust-buffer-order-function))

```
 `centaur-tabs-adjust-buffer-order`
and  the tabs won't be reordered if it is a   centaur-tabs  command 
```
  ;; Don't trigger by centaur-tabs command, it's annoying.
  ;; This feature should trigger by search plugins, such as ibuffer, helm or ivy.
  (unless (string-prefix-p "centaur-tabs" (format "%s" this-command))

```
I change that to 
```
    (unless (or (string-prefix-p "centaur-tabs" (format "%s" this-command))
                ; do not reorder when clicking on the tab bar 
                (string-prefix-p "mouse-drag-header-line" (format "%s" this-command));
             )) 

```

**Comment by ema2159** [comment]
Ok, I'll follow your advice readd the feature! Thanks for letting me know

**Comment by ema2159** [comment]
@jixiuf readded the functionality. It's disabled by default, you need to run a function to enable it, check it out in the Buffer reordering section in the README!

**Comment by ianpan870102** [comment]
> By the way, i fixed the problem of this issue! I just removed the buffer ordering function completely, I found that it was completely unnecessary. I don't think it will break anything but if it does just let me know!

It's working great for me! Thanks for the quick fix (I do prefer my tabs to be in the same order). But it's 
nice that you gave users the option to turn it back on. People have different workflows.

**Comment by jixiuf** [comment]
I suggest don't change the order when clicking on the tab bar like other  centaur-tabs-*  commands.

**Comment by ema2159** [comment]
@jixiuf Yes! I tried your solution but for some reason it didn't work for me. Does it work for you? Please if you find a solution that works would you submit a PR? I'd be glad if you could help me with this one

**Comment by manateelazycat** [comment]
> I suggest don't change the order when clicking on the tab bar like other centaur-tabs-* commands.

If we want not change order when clicking on the tab, should patch like this:  https://github.com/manateelazycat/awesome-tab/commit/4c8ec9b91ce8b55a3c7750b851314781d1d3a310

**Comment by ema2159** [comment]
Hi Andy! (@manateelazycat ) thanks for the help! I really appreciate it!

**Comment by manateelazycat** [comment]
> Hi Andy! (@manateelazycat ) thanks for the help! I really appreciate it!
I am very happy to help. ;)
