### ISSUE TITLE
`(centaur-tabs-line)` issue. Switching from awesome-tab to centaur-tabs.

### ISSUE THREAD

**Issue by FiV0** [ema2159/centaur-tabs#171]
Hey,

I am trying to switch from `awesome-tab` to `centaur-tabs`. All my commands seem to work, but there is some issue rendering the tabbar. I am getting the following error.
```
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp nil) [57 times]
```
It seems to be a similar issue as described here https://github.com/ema2159/centaur-tabs/issues/3. I checked that the background is set for the faces you mentioned there.

The end of the stacktrace if I evaluate `(centaur-tabs-line)` in a ielm repl with `debug-on-error` enabled.
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  propertize(nil centaur-tabs-tab (#<buffer *ielm*> . repl) pointer hand local-map (keymap (tab-line keymap (mouse-2 . centaur-tabs-do-close) (mouse-1 . centaur-tabs-do-select))))
  centaur-tabs-line-format(repl)
  centaur-tabs-line()
  eval((centaur-tabs-line) t)
```

You can find my config here: https://github.com/FiV0/emacs-config/commit/f3e57b92aac1e88b69d43bfe1005695cc6d952d6
OS: ubuntu 20.04
Emacs: 27.2
Centaur-tabs: 20211130.637
Theme: https://github.com/oneKelvinSmith/monokai-emacs

Let me know if you need anything else.

Thanks for your work.

**Comment by FiV0** [comment]
The issue seems to be that `centaur-tabs-active-bar` is nil and that the `'xpm` image type is not available in my emacs. How do I best solve this?

**Comment by nebhrajani-a** [comment]
What's the output of `M-: (image-type-available-p 'xpm)`? If it's `nil` (as expected), your Emacs must not have been compiled with XPM support. IIRC, Ubuntu 20.04's Synaptic 'ships with' Emacs version 26.3 (which is compiled with XPM support), as does the Snap Store's [Emacs (27.2) ](https://github.com/alexmurray/emacs-snap/blob/master/snapcraft.yaml). The solution here is probably to reinstall Emacs with XPM libraries available.

**Comment by FiV0** [comment]
Thanks. I must have installed it from source.
