### ISSUE TITLE
.emacs Centaur's settings not loading properly

### ISSUE THREAD

**Issue by LionyxML** [ema2159/centaur-tabs#180]
Hello there!

If anyone is able to help me.

I have my .emacs configured like this:

```
;; CENTAUR TABS
(require 'centaur-tabs)
;; (global-set-key (kbd "C-<prior>")  'centaur-tabs-backward)
;; (global-set-key (kbd "C-<next>") 'centaur-tabs-forward)
(centaur-tabs-headline-match)
(setq centaur-tabs-style "slant") ;; May be rounded, slant, box, zigzag, chamfer, box, bar or alternate
(setq centaur-tabs-height 32)
(setq centaur-tabs-set-bar 'over) ;; May be left under
(setq x-underline-at-descent-line t)
(setq centaur-tabs-set-modified-marker t)
(setq centaur-tabs-label-fixed-length 12)
(setq centaur-tabs-show-navigation-buttons t)
(setq centaur-tabs-set-icons t)
(setq centaur-tabs-plain-icons nil)
(centaur-tabs-change-fonts "Hack" 150)
(centaur-tabs-mode)
```

As soon as I fire-up emacs I get:

![Captura de Tela 2022-03-13 às 16 10 10](https://user-images.githubusercontent.com/16169950/158075212-6aaf0731-f254-4cdc-ad33-5ca71543bac8.png)

No Line, no slant, apparently wrong height size.

But if I run `centaur-tabs-mode` twice (off and on), this is what I get:

![image](https://user-images.githubusercontent.com/16169950/158075333-621ec90c-bab2-446a-a3f5-368589613ae8.png)
I little less worse.

And sporadically when emacs starts I get slant, and others.

What am I doing wrong?

**Comment by kalindu1** [comment]
<h5>enable the plugin after you configure it</h5>

<h5>like this</h5>
```elisp
(setq centaur-tabs-set-bar 'under)
;; Note: If you're not using Spacmeacs, in order for the underline to display
;; correctly you must add the following line:
(setq x-underline-at-descent-line t)
(centaur-tabs-mode t)

```

**Comment by LionyxML** [comment]
Cool, thanks for your reply.
Indeed `(centaur-tabs-mode t)` makes it work (instead of just `(centaur-tabs-mode)` as I had before.

**Comment by kalindu1** [comment]
My pleasure buddy.
