### ISSUE TITLE
Stupid Question: How to move between tabs (doom emacs)

### ISSUE THREAD

**Issue by rawoke083** [ema2159/centaur-tabs#186]
Hi, great project !
I'm super new to emacs, I'm using a vanila-doom-emacs install. I managed to load the tab packages and it works if I switch between tabs with the mouse. 

Does anyone know, what is the default key bindings to move between tabs on Doom Emacs ?
For the life of me i can't figure it out. The documentations seems to say C-<Prior> and C-<Next> no idea where or how to set that in emacs doom ?

**Comment by CsBigDataHub** [comment]
```
:bind
  ("s-<left>" . centaur-tabs-backward)
  ("s-<right>" . centaur-tabs-forward)
  ("s-<up>" . centaur-tabs-forward-group)
  ("s-<down>" . centaur-tabs-backward-group)
```

This is how i bind it.

**Comment by ema2159** [comment]
@rawoke083 welcome! Please follow @CsBigDataHub advice. That should work. I am usually a fan of using the page-up/page down keys plus control though. You would neet to put the following in the `:bind` section of your `centaur-tabs` configuration.
``` elisp
("C-<prior>" . centaur-tabs-backward)
("C-<next>" . centaur-tabs-forward)
```
