### ISSUE TITLE
Invalid face attribute

### ISSUE THREAD

**Issue by CsBigDataHub** [ema2159/centaur-tabs#187]
Hi @ema2159,

My `*Messages*` buffer is flooded with error below -
```
Invalid face attribute :foreground nil
Invalid face attribute :background nil [5 times]
```

Theme used - `modus-vivendi`

probably the issue is similar to the issue below - https://github.com/ema2159/centaur-tabs/issues/102

**Comment by CsBigDataHub** [comment]
PR to fix in https://github.com/ema2159/centaur-tabs/pull/179

**Comment by ema2159** [comment]
Fixed. Thanks!
