### ISSUE TITLE
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp (Git "~/project")) 

### ISSUE THREAD

**Issue by anildigital** [ema2159/centaur-tabs#188]
I see this when I do 

M-x counsel-ag
then pass "def load(_, _)" as value

Looks like sometimes in centaur-tabs-line fails. If this can be fixed. 

```
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp (Git "~/project")) 
```

Thanks!

**Comment by artemkovalyov** [comment]
This issue also bothers me since a couple of days:
```
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp (Git "/umetra/work/
```

**Comment by slackline** [comment]
I've encountered similar with the following showing repeatedly (number of times varies)...

```
Error during redisplay: (eval (centaur-tabs-line)) signaled (void-function derived-major-mode) [16 times]
```

**Comment by anildigital** [comment]
I have disabled centaur-tabs till this issue is resolved.

**Comment by GeorgesAlkhouri** [comment]
Also happens to me on `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)`

**Comment by Yanhao** [comment]
Maybe this will help
![image](https://user-images.githubusercontent.com/10085564/179723999-20aea805-e90d-4649-8052-ac65d6c9add2.png)

**Comment by anildigital** [comment]
@Yanhao Seems it is working. I didn't see that annoying message yet. Thanks!

**Comment by anildigital** [comment]
@ema2159 Could you add the fix suggested by @Yanhao Thanks!

**Comment by ema2159** [comment]
Hi! I am back. I will review this and push it soon. If I understand correctly this occurs because of recent changes in project.el, though this is for more recent versions of Emacs. I think though that using `(nth 2 (project-current))` is not the best idea for backward compatibility reasons. Probably using `(car (last (project-current))` is a better idea.

**Comment by liar666** [comment]
> Maybe this will help ![image](https://user-images.githubusercontent.com/10085564/179723999-20aea805-e90d-4649-8052-ac65d6c9add2.png)

Couldn't you just publish the code rather than a picture? That would be lighter for the GH platform and easier for the readers/users to copy/apply the modification.
