### ISSUE TITLE
Attempting to customize centaur tabs selected tab face consistantly crashes emacs

### ISSUE THREAD

**Issue by michaelmrose** [ema2159/centaur-tabs#19]

**Comment by michaelmrose** [comment]
27.0.5 built with lucid toolkit on Manjaro current running a 4.20 kernel version with i3wm and intel graphics. I'm running Emacs in daemon mode. I use customize-apropos-faces find centaur click on the selected tab face start typing and either in the middle of typing or upon applying the Emacs daemon crashes.

I'd be happy to provide any data that might be of assistance I just don't know what you might need.

**Comment by ema2159** [comment]
That's a really really odd problem, I've never been able to crash Emacs. Is there any way you could collect an stack trace or something that gives me a little bit more information?

**Comment by michaelmrose** [comment]
It also appears  to work the same outside of daemon mode. This is what I get.
Warning: Cannot convert string "9x15" to type FontStruct
Warning: Unable to load any usable ISO8859 font
Warning: Unable to load any usable ISO8859 font
Warning: Missing charsets in String to FontSet conversion
Fatal error 11: Segmentation fault
Backtrace:
emacs(+0x135e4f)[0x56291f414e4f]
emacs(+0x3cfb7)[0x56291f31bfb7]
emacs(+0x3d40b)[0x56291f31c40b]
emacs(+0x134449)[0x56291f413449]
emacs(+0x1344ca)[0x56291f4134ca]
/usr/lib/libpthread.so.0(+0x124d0)[0x7f2f32a874d0]
/usr/lib/libXaw3d.so.8(+0x1ab54)[0x7f2f34ca7b54]
/usr/lib/libXaw3d.so.8(+0x1b2b4)[0x7f2f34ca82b4]
/usr/lib/libXt.so.6(+0x1ab9c)[0x7f2f34a23b9c]
/usr/lib/libXt.so.6(+0x1b528)[0x7f2f34a24528]
/usr/lib/libXt.so.6(_XtCreateWidget+0xcf)[0x7f2f34a249ef]
/usr/lib/libXt.so.6(XtCreateManagedWidget+0xda)[0x7f2f34a24dda]
/usr/lib/libXaw3d.so.8(+0x19430)[0x7f2f34ca6430]
/usr/lib/libXt.so.6(+0x1ab9c)[0x7f2f34a23b9c]
/usr/lib/libXt.so.6(+0x1b528)[0x7f2f34a24528]
/usr/lib/libXt.so.6(_XtCreateWidget+0xcf)[0x7f2f34a249ef]
/usr/lib/libXt.so.6(XtCreateManagedWidget+0xda)[0x7f2f34a24dda]
emacs(+0x23a180)[0x56291f519180]
emacs(+0x23ae5b)[0x56291f519e5b]
emacs(+0x233c78)[0x56291f512c78]
emacs(+0x9ca71)[0x56291f37ba71]
emacs(+0x19aaa3)[0x56291f479aa3]
emacs(+0x1d5cdb)[0x56291f4b4cdb]
emacs(+0x19aa2f)[0x56291f479a2f]
emacs(+0x1d5cdb)[0x56291f4b4cdb]
emacs(+0x19aa2f)[0x56291f479a2f]
emacs(+0x1d5cdb)[0x56291f4b4cdb]
emacs(+0x19aa2f)[0x56291f479a2f]
emacs(+0x19ae7a)[0x56291f479e7a]
emacs(+0x1a3edc)[0x56291f482edc]
emacs(+0x19aaa3)[0x56291f479aa3]
emacs(+0x1d5cdb)[0x56291f4b4cdb]
emacs(+0x19aa2f)[0x56291f479a2f]
emacs(+0x1d5cdb)[0x56291f4b4cdb]
emacs(+0x19aa2f)[0x56291f479a2f]
emacs(+0x1972b2)[0x56291f4762b2]
emacs(+0x19aaa3)[0x56291f479aa3]
emacs(+0x198734)[0x56291f477734]
emacs(+0x19aaa3)[0x56291f479aa3]
emacs(+0x1d5cdb)[0x56291f4b4cdb]
emacs(+0x19aa2f)[0x56291f479a2f]
...
fish: “emacs” terminated by signal SIGSEGV (Address boundary error)

**Comment by michaelmrose** [comment]
Scratch all this this is a bug with this build and any usage of customization. I just haven't had any opportunity to use this since I switched to lucid relatively recently.

**Comment by ema2159** [comment]
Ok, glad it wasn't centaur-tabs! Thanks and I hope you figure it out!
