### ISSUE TITLE
Icons don't show up

### ISSUE THREAD

**Issue by 0poss** [ema2159/centaur-tabs#190]
After installing [`all-the-icons`](https://github.com/domtronn/all-the-icons.el) as indicated in its [`README.md`](https://github.com/domtronn/all-the-icons.el/blob/master/README.md) (including doing a `M-x all-the-icons-install-fonts RET`) and [`centaur-tabs`](https://github.com/ema2159/centaur-tabs) as recommended, no icons are showing up in the tabs. See : 
![image](https://user-images.githubusercontent.com/67114640/189619654-ed545e96-d52b-4ae4-ae18-f6e49c95b84d.png).

The icons show up as expected when using `all-the-icons-icon-for-file`. See (executed using `M-x eval-buffer RET`) : 
![image](https://user-images.githubusercontent.com/67114640/189620510-b8b16436-74f6-4152-b0ac-603337838339.png)

How can I try to solve this issue ? Thanks a lot !

You can find my emacs config (with the interesting part highlighted) [here](https://github.com/0poss/dotfiles/blob/7732e8f59d9a55a96a14fc80bff5d1b05d399031/emacs.d/init.el#L114-L124).

**Comment by ema2159** [comment]
You're not enabling the icons in your configuration. Please follow the instructions presented in [this](https://github.com/ema2159/centaur-tabs#tab-icons) and [this](https://github.com/ema2159/centaur-tabs#my-personal-configuration) section.
