### ISSUE TITLE
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp vc)

### ISSUE THREAD

**Issue by e190** [ema2159/centaur-tabs#191]
GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.17.6) of 2022-04-13
GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.23, cairo version 1.13.1) of 2022-09-21

I get errors when I open C files, but I don't get errors when I open Lisp files, such as init.el .
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp vc) [198 times]

**Comment by zbelial** [comment]
I have the same problem. You can modify `centaur-tabs-project-name` to work around this problem. 
```elisp
(defun centaur-tabs-project-name ()
  "Get project name for tabs."
  (let ((project-name (cdr (project-current))))
    (if project-name
	(format "Project: %s" (expand-file-name project-name))
      centaur-tabs-common-group-name)))
```

**Comment by zbelial** [comment]
As I said in #192 , it seems in Emacs 29, `project-current` returns something with different format.

**Comment by ema2159** [comment]
Yes. I tried to solve it in a way that backward compatibility was not compromised, but apparently, it didn't work. Can you please show me what is displayed when you evaluate `(project-current)`? You can do `M-x (message "%s" (project-current))`.

**Comment by e190** [comment]
The results of (project-current) are not problematic.

```
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp vc) [29 times]
(vc . ~/work/l508-test/)
"(vc . ~/work/l508-test/)"Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp vc)
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp vc) [93 times]
```

**Comment by ema2159** [comment]
Hmmm, I wonder what is it then, because that was the [only change](https://github.com/ema2159/centaur-tabs/commit/0e8bd654dd505ae8a90adf9d1e554361d4f3c3c6). Could you go to the problematic buffer, do this: `M-: (message "%s" (project-current))`, and post here what is printed in the minibuffer please?

**Comment by zbelial** [comment]
In Emacs 28, `(message "%s" (project-current))` will return something like `(vc . ~/work/l508-test/)`, which I get from e190's reply.  

You can see that it's not a proper list. But in Emacs 29, the result is a proper list. So maybe the function `centaur-tabs-project-name` can be modified in the following way? 
```elisp
          (defun centaur-tabs-project-name ()
              "Get project name for tabs."
              (let* ((project-current (project-current))
                     (project-name (if (proper-list-p project-current)
                                       (car (last project-current))
                                     (cdr project-current))))
                (if project-name
	            (format "Project: %s" (expand-file-name project-name))
                  centaur-tabs-common-group-name)))
```

It works for me in Emacs 28.  WDYT?

**Comment by ema2159** [comment]
@zbelial thanks a lot! The issue is that in Emacs versions below 29, `(project-current)` returns a cons cell, whereas in more recent versions, a list is returned instead. With the workaround you proposed it should now work just fine.
