### ISSUE TITLE
icons in tabs used to show in terminal, but no longer

### ISSUE THREAD

**Issue by bsferrazza** [ema2159/centaur-tabs#196]
I'm using centaur-tabs for the first time in a year and while I was able to have the file type icons show up from all-the-icons before in my tabs using a terminal emulator, they are no longer showing up.

Looks like it now checks if we're in GUI mode? It worked just fine in Terminal before, why the change?

```
(icon (if (and centaur-tabs-set-icons
			(display-graphic-p)
			(not centaur-tabs--buffer-show-groups))
```

**Comment by ema2159** [comment]
It seems this was added in the _Compatibility with Emacs Daemon Mode_ PR. Since I personally don't use Emacs in Terminal, I didn't notice this. Does removing the `(display-graphic-p)` solves the issue? If so, I think I'll just re-enable it, since I don't see any reason not to.

**Comment by bsferrazza** [comment]
@ema2159 yes, removing (display-graphic-p) solves the issue
