### ISSUE TITLE
Support for Haki Theme

### ISSUE THREAD

**Issue by gopar** [ema2159/centaur-tabs#212]
Theme: https://github.com/idlip/haki

How it currently looks:
![Screenshot 2023-07-15 at 3 20 13 PM](https://github.com/ema2159/centaur-tabs/assets/1545083/232e08ca-25b2-4091-bdfe-098dd489c633)

Would provide a PR myself but rather rusty in elisp and don't know much about faces in emacs.
Thanks for the package :)

**Comment by swarnendubiswas** [comment]
It should be the other way round, isn't it? Haki theme should support `centaur-tabs`.
