### ISSUE TITLE
extra space after close button

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#22]
there's a space before file an icon in the tab, but no space after close and modified buttons. I can add it manually though:

```emacs-lisp
(setq centaur-tabs-set-modified-marker t
      centaur-tabs-modified-marker "● "
      centaur-tabs-close-button (concat centaur-tabs-close-button " ")
```

but it adds underline on that space when hovering:

![image](https://user-images.githubusercontent.com/19470159/61186239-a2875380-a66b-11e9-8594-009991865683.png)

I guess this can also be solved with different face settings for hovered state, but I think there should be some space after close button in the first place

**Comment by ema2159** [comment]
You could disable the underline by modifying the `centaur-tabs-close-mouse-face` face. The thing is, if I put a space there by default I think it takes up too much space that without the icons enabled looks even bigger. Thanks for enjoying my package by the way!

**Comment by ema2159** [comment]
Tell me if that works for you. If it does, may I close this issue?

**Comment by andreyorst** [comment]
> if I put a space there by default I think it takes up too much space that without the icons enabled looks even bigger. 

The space should be added only when close button is enabled:

```
| name |
 ^    ^       2 spaces
| @ name |
 ^ ^    ^     3 spaces
| name x |
 ^    ^ ^     3 spaces
| @ name x |
 ^ ^    ^ ^   4 spaces
```

**Comment by ema2159** [comment]
Hmmmm I'm no sure. Given it's a fairly subjective thing lets make it through democracy. If somebody wants the extra space vote rocket, if someone considers it unnecessary, vote hooray. Let's give it two weeks

**Comment by andreyorst** [comment]
I guess it's no for now?

**Comment by ema2159** [comment]
I guess I pulled out the worst votation of history jaja. I'll add a custom for you!

**Comment by ema2159** [comment]
Thinking it better, having that extra space do look better so I'll add it
