### ISSUE TITLE
Centaur-tabs does not show in help-mode/helpful-mode

### ISSUE THREAD

**Issue by zhenhua-wang** [ema2159/centaur-tabs#229]
This issue also occurs in `emacs -Q`. I am using `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.18.0) of 2023-11-21`;

**Comment by zhenhua-wang** [comment]
Customizing `centaur-tabs-hide-tab` solves it

**Comment by erikmd** [comment]
FTR: since PR #220, centaur-tabs now shows tabs in help-mode & helpful-mode, so no manual tweak is needed anymore.
