### ISSUE TITLE
Hydras get unwanted extra header

### ISSUE THREAD

**Issue by Khoulaiz** [ema2159/centaur-tabs#24]
I am using [hydra](https://github.com/abo-abo/hydra) and centaur tabs together. When I activate a hydra, the hydra content gets an unwanted line on the header which messes up the layout (see screenshot 1). When I mouse click the blue line, it vanishes and the layout looks like the way it should be. Deactivating centaur tabs fixes the issue. I would like to turn off centaur tabs for hydra windows, but I don't know how to do that. Any help would be appreciated.

<img width="640" alt="Screenshot 1" src="https://user-images.githubusercontent.com/894816/61201397-a905e180-a6e4-11e9-9de2-e9ae143bf052.png">

<img width="642" alt="Screenshot 2" src="https://user-images.githubusercontent.com/894816/61201403-ac996880-a6e4-11e9-9748-bbe84875f52a.png">

**Comment by ema2159** [comment]
I'm using hydra with `centaur-tabs` too. Although I'm mot that sure (its been some time since I configured it) I think I just added a hook to `centaur-tabs-local` which will disable centaur tabs  in any desired buffer! Tell me if this works for you

**Comment by Khoulaiz** [comment]
No, it's not working for me or I simple don't know how to do it. AFAIK there is no hydra-mode and the hydra-popup is not a regular buffer with a mode that you can bind a hook on. 
I am sure it is somehow possible, but it is not as easy as for the normal cases and that's why I created this issue. I would love to see your config for it. :-)

**Comment by akirak** [comment]
I encountered the same issue. I ended up configuring hydra to use posframe.

**Comment by ema2159** [comment]
Wow I had this problem all along and somehow I didn't noticed!. I'm asking @abo-abo

**Comment by jixiuf** [comment]
try custom `centaur-tabs-hide-tab-function`

```
(defun vmacs-show-tabbar-p(&optional buf redisplay)
  (let ((show t))
    (with-current-buffer (or buf (current-buffer))
      (cond
       ((char-equal ?\  (aref (buffer-name) 0))
        (setq show nil))
       ((member (buffer-name) '("*Ediff Control Panel*"
                                "\*Flycheck error messages\*"
                                "\*Gofmt Errors\*"))
        (setq show nil))
       (t t))
      (unless show
        ;; (kill-local-variable 'header-line-format)
        (setq header-line-format nil)
        (when redisplay (redisplay t))
        )
      show)))

(defun vmacs-hide-tab-p(buf)
  (not (vmacs-show-tabbar-p buf t)))

(setq centaur-tabs-hide-tab-function #'vmacs-hide-tab-p)

```

**Comment by ema2159** [comment]
Abo abo told me that the buffer is called *LV*, so I think that a using a hide rule for that should work. Let me try

**Comment by ema2159** [comment]
@jixiuf which part of that rule is the one that disables the header line in the hydra? Maybe I could try to add it to the default function

**Comment by ema2159** [comment]
Found a solution. I'll submit a PR to abo-abo's lv package

**Comment by ema2159** [comment]
It should be fixed with the next hydra's lv update. I'm closing this issue now

**Comment by Khoulaiz** [comment]
Works for me, thanks!
