### ISSUE TITLE
ability to tab "out" of "hidden" buffers

### ISSUE THREAD

**Issue by cburroughs** [ema2159/centaur-tabs#28]
I'll admit that this is an attempt to replicate the -- possibly quirky -- behavior I like from a circa 2003 copy of tabbar.

I've defined `centaur-tabs-hide-tab` to hide several buffers, such as the scratch buffer or messages.  This keeps `centaur-tabs-forward/backward` from going*into* those buffers (yeah!).  However, I'd still like to be able to tab *out* of those buffers.  That is  `centaur-tabs-forward` from the scratch buffer would take me to the first buffer that isn't hidden from centaur-tabs.  Right now, that command appears to do nothing in a hidden buffer

**Comment by ema2159** [comment]
True, I'll search a fix for this, it should't be too hard

**Comment by Compro-Prasad** [comment]
@cburroughs You could use `next-buffer` and `previous-buffer`.

**Comment by ema2159** [comment]
@cburroughs sorry I forgot about this one. I solved it. Tell me if it's alright.

**Comment by cburroughs** [comment]
Looking good to me; thanks!
