### ISSUE TITLE
options for sorted tabs

### ISSUE THREAD

**Issue by cburroughs** [ema2159/centaur-tabs#29]
I'll admit that this is an attempt to replicate the -- possibly quirky -- behavior I like from a circa 2003 copy of tabbar.

I know the more typical modern behavior is for tabs to be ordered by whenever you opened them.  Would it be possible to have a hook/option to keep the tabs lexographically sorted?

**Comment by ema2159** [comment]
You'll have to set a rule overwriting the `centaur-tabs-buffer-reordering` function in which the tabs were ordered lexographically.

**Comment by ema2159** [comment]
Please feel free to reopen the issue if you need further assistance

**Comment by cburroughs** [comment]
I can't seem to find a function by that name.  Did you mean that I need to call `centaur-tabs-enable-buffer-reordering` and then define a new `centaur-tabs-adjust-buffer-order-function`?

**Comment by ema2159** [comment]
Sorry, it is the variable `centaur-tabs-adjust-buffer-order-function`, which receives a function that establishes rules for buffer ordering. I you manage to create a function to order tabs lexicographically please let me now so I can document it or even add it to the package
