### ISSUE TITLE
consider making non file buffers that show the same projectile-project-root group with the associated project by default

### ISSUE THREAD

**Issue by michaelmrose** [ema2159/centaur-tabs#30]
Example in cider clojure repls should group with the project ideally.  This can be configured in a custom function in theory but ideally but when grouping buffers by project one would expect such buffers to be grouped by default as they are as much part of the project as the files.

If utilizing this method of grouping one ends up frequently switching between groups without reason.

**Comment by ema2159** [comment]
Would you give me a more detailed example? Like with the file structure and everything? Are you using the group by projectile s project function?

**Comment by michaelmrose** [comment]
(use-package centaur-tabs
  :config

  (centaur-tabs-mode t)
  (centaur-tabs-group-by-projectile-project)

  (setq centaur-tabs-height 32
        centaur-tabs-style "rounded"
        centaur-tabs-cycle-scope 'tabs
        centaur-tabs-set-icons t
        centaur-tabs--buffer-show-groups nil
        centaur-tabs-set-modified-marker t
        centaur-tabs-modified-marker "λ"
        )


  (defun centaur-tabs-hide-tab (x)
    (let ((name (format "%s" x)))
	    (or
	     (string-prefix-p "*epc" name)
	     (string-prefix-p "*helm" name)
	     (string-prefix-p "*Compile-Log*" name)
	     (string-prefix-p "*lsp" name)
       (string-prefix-p "*mu4e" name)
	     (and (string-prefix-p "magit" name)
	          (not (file-name-extension name)))
	     )))

  (global-set-key (kbd "<f21>") 'centaur-tabs-backward)
  (global-set-key (kbd "<f23>") 'centaur-tabs-forward)
  (global-set-key (kbd "<f26>") 'centaur-tabs-backward)
  (global-set-key (kbd "<f27>") 'centaur-tabs-forward)
  (global-set-key (kbd "<f28>") 'centaur-tabs-counsel-switch-group)
  )

Given a directory tree that looks like

.
├── example.mkv
├── makefile
├── project.clj
├── rdr-0.1.0-SNAPSHOT-standalone
├── rdr.org
├── README.md
├── release
├── resources
├── src
│   └── rdr
│       ├── calibre.clj
│       ├── core.clj
│       ├── scratch.clj
│       └── utils.clj
├── test
│   └── rdr
│       └── core_test.clj
├── testlibrary
│   ├── Drew Neil
│   │   └── atestbook (2)
│   │       ├── atestbook - Drew Neil.pdf
│   │       ├── cover.jpg
│   │       └── metadata.opf
│   ├── metadata.db
│   ├── metadata_db_prefs_backup.json
│   └── Unknown
│       └── lambda-calculus.dvi (1)
│           ├── cover.jpg
│           ├── lambda-calculus.dvi - Unknown.pdf
│           └── metadata.opf
└── usage.txt

11 directories, 20 files

Readme.md will end up in the other group and the actual cider repl buffer will end up in a Term group. This is  quite odd. Its possible to manually sort things manually into more reasonable groups for example I have

(defun centaur-tabs-buffer-groups ()
  (list
   (cond
    ((projectile-project-p)
     (projectile-project-name))
    ((string-equal "*scratch*" (buffer-name))
     ".emacs.d")
    ((or (string-equal "*" (substring (buffer-name) 0 1))
         (memq major-mode '(magit-process-mode
			                      magit-status-mode
			                      magit-diff-mode
			                      magit-log-mode
			                      magit-file-mode
			                      magit-blob-mode
			                      magit-blame-mode
			                      )))
     "Emacs")
    ((memq major-mode '(org-mode
		                    org-agenda-clockreport-mode
		                    org-src-mode
		                    org-agenda-mode
		                    org-beamer-mode
		                    org-indent-mode
		                    org-bullets-mode
		                    org-cdlatex-mode
		                    org-agenda-log-mode
		                    diary-mode))
     "OrgMode")
    (t
     (centaur-tabs-get-group-name (current-buffer))))))

Which seems to have the desired result and kudos for making it so flexible but I think the default project sorting could use help.

**Comment by ema2159** [comment]
That's odd. If the README.md for example is from the same project, it should be grouped there by default. If you use Ivy/Helm/Ido to switch group, what groups appear in it?

**Comment by ema2159** [comment]
How is this going brother? Do you still have this issue?

**Comment by ema2159** [comment]
Given this issue is inactive, I'll close it. Open it if you consider it's still necessary.
