### ISSUE TITLE
Disable tabs for *Completion* buffer

### ISSUE THREAD

**Issue by paulie4** [ema2159/centaur-tabs#31]
Is it just me, or do other people think the Centaur tabs make the `*Completion*` buffer much less useful? When it's enabled, there's only one line of values, and the rest is the tabs and this boilerplate:
```
Click on a completion to select it.
In this buffer, type RET to select the completion near point.

Possible completions are:
```

I think the only fix needed for this is to edit https://github.com/ema2159/centaur-tabs#disable-centaur-tabs-in-selected-buffers so it recommends to users to use this:
```
(add-hook 'completion-list-mode-hook 'centaur-tabs-local-mode)
```

**Comment by ema2159** [comment]
What is the *Completion* buffer? I think I've never used or seen it jaja

**Comment by paulie4** [comment]
When you are searching to open a file (i.e. `C-x C-f`), the first time you hit tab, it will say `[Complete, but not unique]`. The second time you hit it, the `*Completion*` buffer will open with all the matching files. Also, if you are in the minibuffer to enter a command (i.e. via `M-x`) or to switch an already open buffer (via `C-x b`), just pressing tab once will open up the `*Completion*` buffer with all the matching commands or buffers, respectively, see also https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion.html

**Comment by ema2159** [comment]
Ok, now I see. It's been a long time since I've used Ido. The solution you propose is the correct one but given that the completion buffer is an Emacs default I just added a patch that hides it by default without having to add the hook.

**Comment by paulie4** [comment]
Thanks!

P.S. since your commit doesn't reference this issue number, I'll reference your commit here:
https://github.com/ema2159/centaur-tabs/commit/d8fd043577bedd94f747e31f9760780d819fd295

**Comment by ema2159** [comment]
Thanks man! Thank you for using my package :D!
