### ISSUE TITLE
Generalization of buffer groups

### ISSUE THREAD

**Issue by akirak** [ema2159/centaur-tabs#32]
Hello, I'm quite interested in this package since it has appeared on Emacs Reddit.

I've noticed that *buffer groups* are the most central to this package and that tabs are just a way to present the buffer groups, To name a few, the following packages are well-known alternatives that implement what I call buffer groups:

- https://github.com/bmag/emacs-purpose
- https://github.com/nex3/perspective-el

By adding a strong support for buffer groups like those packages, I think centaur-tabs can potentially constitute an integral part of Emacs workflow. However, it may be beyond the scope of the package... Otherwise, it may be a good idea to support an external buffer group manager through a modular design. That is, you can define buffer groups in somewhere else (or another package) and let centaur-tabs present tabs based on the groups. It may help reduce the code in this package and focus on presentation.

What do you think?

**Comment by ema2159** [comment]
I completely agree! I with this package I didn't just wanted to implement some eye candy package that looks nice, but also a functional package that could help to organize different workspaces. As it is now, there is a variable which determines the function that stablishes the rules for buffer ordering. What I would really like is to implement a better API for other packages to stablish buffer grouping rules in an easy, configurable way.

**Comment by ema2159** [comment]
By the way, do you have any ideas that you would like to share?

**Comment by akirak** [comment]
I was thinking of adding several features for buffer group management to this package, but since the package is currently under a heavy development, so I probably won't work on implementation soon. Below are examples:

- Switching to a buffer in the current group with a single key.
- Switching to a group faster with a single key.

[frog-menu](https://github.com/clemera/frog-menu) may help these problems, but I am not sure if it is the right solution.

When I implemented [frame-workflow](https://github.com/akirak/frame-workflow), I was suggested using eieio, and actually it made the code cleaner. Eieio may be useful for implementing buffer groups. Otherwise, you could use `cl-defstruct`.

**Comment by ema2159** [comment]
> Switching to a buffer in the current group with a single key

This is possible, I need to document it, thanks for reminding me. This can be done with numbered key bindings like for example, if I did C-c t 5 it changes to the 5th visible buffer 

> Switching to a group faster with a single key.

I use Ivy to do so. I'm not sure if it's the optimal way. Maybe integrating frog-menu would be a nice feature

**Comment by akirak** [comment]
Thanks. There are some other features I may wish to implement like saving and restoring layouts defined in terms of buffer groups, but I am not sure if it should be part of this package. I would prefer a tab bar presentation provided as a separate package from the workspace manager.

**Comment by ema2159** [comment]
What I propose is to implement a simple way to create buffer groups so it is easy for other work space managers to create them. A lot of people use Eyeproyse, perspective or persp-mode.el so it would be nice to create a nice interface for users to integrate both functionalities

**Comment by archcst** [comment]
Hi @ema2159 , I dug this repo for solution of perspective.el integration and I found this, I'm here to ask have you created the interface for perspective as you discussed above.

According to the top issue in the issues list, I understand that you are busy on life like the original awesome-tab author hence you might not get the time to maintain this package recently.

Any way, a reply is worth a shot, it will be highly appreciated if you could provide any information about this.
