### ISSUE TITLE
Possible to configure the fonts?

### ISSUE THREAD

**Issue by ianpan870102** [ema2159/centaur-tabs#33]
As titled. Since I'm using a proportional San Francisco font in Treemacs, I'd love to have the variable pitch experience in tabs as well. Is there a one-liner (a master default face) that controls the font behaviour of Centaur Tabs?

Cheers in advance!

**Comment by ema2159** [comment]
I haven't done that personally yet, but maybe with a `(set-face-attribute centaur-tabs-selected nil :family [THE FONT FAMILY YOU WANT])` and doing so for the other faces?

**Comment by ema2159** [comment]
That as a temporary fix, the idea of having a way of generally changing the fonts is a nice addition that I'll add soon

**Comment by ianpan870102** [comment]
Thanks for the suggestion, I improved it using a dolist-loop. For others looking for a solution, here's my 2-cents:

```
    (dolist (centaur-face '(centaur-tabs-selected
                            centaur-tabs-selected-modified
                            centaur-tabs-unselected
                            centaur-tabs-unselected-modified))
      (set-face-attribute centaur-face nil :family "arial" :height 140))
```

**Comment by ema2159** [comment]
I'm reopening this so I don't forget to do it

**Comment by ianpan870102** [comment]
Sure thing! Sounds great :)
