### ISSUE TITLE
uniquify settings unconditionally overridden

### ISSUE THREAD

**Issue by cburroughs** [ema2159/centaur-tabs#34]
https://github.com/ema2159/centaur-tabs/blame/master/centaur-tabs.el#L1977..L1982

```
;; Uniquify tab name when open multiple buffers with same filename.
(setq uniquify-separator "/")
(setq uniquify-buffer-name-style 'post-forward-angle-brackets)
(setq uniquify-after-kill-buffer-p t)
```

These settings seem fine, but I'm not sure why centaur-tabs needs to override them.  If a user wants a different `uniquify-buffer-name-style`, is it intended that they should have to use `(eval-after-load 'centaur-tabs-mode`?

**Comment by ema2159** [comment]
Not quite sure, that's work from the previous author. I'll have to check it and then come back to you with an answer.

**Comment by ema2159** [comment]
> https://github.com/ema2159/centaur-tabs/blame/master/centaur-tabs.el#L1977..L1982
> 
> ```
> ;; Uniquify tab name when open multiple buffers with same filename.
> (setq uniquify-separator "/")
> (setq uniquify-buffer-name-style 'post-forward-angle-brackets)
> (setq uniquify-after-kill-buffer-p t)
> ```
> 
> These settings seem fine, but I'm not sure why centaur-tabs needs to override them. If a user wants a different `uniquify-buffer-name-style`, is it intended that they should have to use `(eval-after-load 'centaur-tabs-mode`?

It seems that the previous author hardcoded them. I'm not a huge fan of this so maybe I'll delete this lines so the default/user-set uniquify configuration is used.
