### ISSUE TITLE
Ability to customize mouse bindings

### ISSUE THREAD

**Issue by fiddlerwoaroof** [ema2159/centaur-tabs#35]
Hi, I'd like to be able to customize the mouse bindings: particularly, I'd like to make mouse-2 (the middle mouse button) kill the currently selected tab but there doesn't seem to be any obvious way to do that as is.

**Comment by ema2159** [comment]
Hi! I think that making the mouse bindings customizable would not be practical, but I can add the functionality of closing the tabs with mouse-2. Would that be ok for you?

**Comment by fiddlerwoaroof** [comment]
Sounds good  thanks.

**Comment by ema2159** [comment]
Done! Just wait for the next update
