### ISSUE TITLE
Support for chocolate theme

### ISSUE THREAD

**Issue by Compro-Prasad** [ema2159/centaur-tabs#39]
https://github.com/SavchenkoValeriy/emacs-chocolate-theme

**Comment by ema2159** [comment]
@SavchenkoValeriy Hi! Could you please theme my plugin in your theme package? I usually follow the following guidelines:

- If you use `solaire-mode`, the `centaur-tabs-unselected` faces background must match the `solaire-default` background color.
- The color from the modified marker and the bar must match.

Here's the kaolin-themes configuration for reference:

``` elisp
    (centaur-tabs-default    (:background bg0 :foreground bg0))
    (centaur-tabs-selected   (:background bg1 :foreground fg1))
    (centaur-tabs-unselected (:background bg0 :foreground comment))
    (centaur-tabs-selected-modified   (:background bg1 :foreground todo))
    (centaur-tabs-unselected-modified (:background bg0 :foreground todo))
    (centaur-tabs-active-bar-face (:background keyword))
    (centaur-tabs-modified-marker-selected (:inherit 'centaur-tabs-selected :foreground keyword))
    (centaur-tabs-modified-marker-unselected (:inherit 'centaur-tabs-unselected :foreground keyword))

```

**Comment by SavchenkoValeriy** [comment]
@ema2159 Hi, interestingly enough I was doing it today 😆 
Here is the original issue: https://github.com/SavchenkoValeriy/emacs-chocolate-theme/issues/4
Implementation is on a branch for now.

I'll check about the `solaire-mode`

PS you've made a great package

**Comment by ema2159** [comment]
@SavchenkoValeriy thanks for your kind words! Your theme is pretty nice also! 
The centaur-tabs theming that you've implemented is completely fine and looks really cool. When you theme solaire, you may use the same color as the unselected tabs color.
Let me know when you finish it so I add your package to the currently themed list!

**Comment by SavchenkoValeriy** [comment]
@ema2159 ✅
