### ISSUE TITLE
Wrong way to initialize variables

### ISSUE THREAD

**Issue by Compro-Prasad** [ema2159/centaur-tabs#40]
https://github.com/ema2159/centaur-tabs/blob/a5f9934854c21a94189435bd6aebc60629623b02/centaur-tabs.el#L1748

It should go into `defvar` or it makes hard to override these values.

**Comment by ema2159** [comment]
Those variables are not meant to be overriden, given that those assignments are specific to the functions (`(centaur-tabs-buffer-init)`, `(centaur-tabs-buffer-quit)`...). The variables are properly declared at the top of the file

**Comment by Compro-Prasad** [comment]
Then please extend the functionality of `centaur-tabs-tab-label-function`. I want to have different parts of the buffer name trimmed off on the tabs. For example I use Telegram and the chat buffer names are too long: `Telega-supergroup@vlang_en: The V Programming Language`. I want this to be able to customize. If not I could open a PR. Do you want me to open a PR?

**Comment by Compro-Prasad** [comment]
I think we should have a `centaur-tabs-tab-name-function` and `centaur-tabs-tab-tooltip-function`. This will help in having a configurable way to show tabs.

**Comment by ema2159** [comment]
Maybe, although I think it's a too specific use case. I may look if there's someway to make it more configurable. For now, there's a `centaur-tabs-fixed-length` customization which truncates the tabs to a customizable amount of characters.

**Comment by Compro-Prasad** [comment]
That length does help in truncating but when I hover a tab it should reveal the full buffer name.

**Comment by ema2159** [comment]
You use my package in ways that in incredibly particular ways jaja. I'll try to make those functions customizable so you're able to use them as you like.

**Comment by Compro-Prasad** [comment]
Its a first impression thing. If new Emacs users find something missing then they will assume Emacs isn't powerful enough. What I suggest is just something I have gathered from other IDEs/editors.
