### ISSUE TITLE
centaur-tabs + doom-modeline height faces leads to scrollbar dancing madness

### ISSUE THREAD

**Issue by cburroughs** [ema2159/centaur-tabs#41]
Approximate steps to reproduce: 
* Use centaur-tabs and doom-modeline
 * Customize the modeline height faces
 * Open multiple elisp files
 * Vertically split into two windows
 * Switch to the right window
 * Type something
 * Switch tabs
 * Switch back to the left window
 * Type Type Type
 * The cursor will disappear and the left scrollbar will start oscillating in a little dance

I think this is close to a minimal config:
```elisp
;; GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8)

(require 'package)
(setq package-enable-at-startup nil)
(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")
        ("melpa-stable" . "https://stable.melpa.org/packages/")
        ("melpa" . "https://melpa.org/packages/")))

(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))
(require 'bind-key)

(use-package centaur-tabs
  :ensure t
  :demand
  :bind
  ([(C-S-iso-lefttab)] . centaur-tabs-backward)
  ([(control tab)] . centaur-tabs-forward)
  :config
  (centaur-tabs-mode t))


(use-package doom-modeline
  :ensure t
  :pin melpa-stable
  :hook (after-init . doom-modeline-mode)
  :config
  (set-face-attribute 'mode-line nil :height 105)
  (set-face-attribute 'mode-line-inactive nil :height 105))
```

**Comment by cburroughs** [comment]
Example video: http://us-east.manta.joyent.com//cburroughs/public/tmp/output.mp4

**Comment by ema2159** [comment]
Man you're winning the `centaur-tabs` award on submitting the hardest issues jaja. I'll have to check this since it may depend on other things like your distro and windows manager etc.

**Comment by Compro-Prasad** [comment]
Not able to reproduce this in Emacs 27.0.50. My scroll bar seems to just get smaller as I type continuously. Anyway, I have scroll bars turned off by default.

**Comment by cburroughs** [comment]
* I get the same behavior with `GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8)` built from 2a82b5542661d181933b11f9c72323ef5da708ef
 * With scrollbars disabled, there is no scrollbar to do a dance, but the cursor will still disappear for a while when doing the above steps.

**Comment by ema2159** [comment]
I'm unable to reproduce in my system, and I'm not quite sure this is fixable (at least through `centaur-tabs` code). If I'm not wrong, it's a problem with the desktop environment (If I'm not wrong, you're using XFCE4).

**Comment by Compro-Prasad** [comment]
@cburroughs Your reproduction steps seem a bit vague. Can you re-write the steps to the point where the cursor is permanently invisible? I also don't use blinking cursor. If that is an issue then mention the state of the cursor too.

**Comment by ema2159** [comment]
@cburroughs I'll have to close this issue for now due to inactivity. Please re-open it if you consider it's necessary, although I'm not sure if it is fixable given it's a system specific problem.

**Comment by cburroughs** [comment]
Understood.

For what it's worth I'm able to work around the issue now, and suspect it is (was?) some combination of domtronn/all-the-icons.el#106 and seagle0128/doom-modeline#215

**Comment by ema2159** [comment]
domtronn/all-the-icons.el#106 this one is a classic haha! It has caused so many problems it's unbelievable

**Comment by ema2159** [comment]
Thank's for your feedback and glad you were able to work around it!
