### ISSUE TITLE
centaur-tabs-close-button nil not working properly

### ISSUE THREAD

**Issue by joca-bt** [ema2159/centaur-tabs#42]
There's some issue when `(setq centaur-tabs-close-button nil)`.

Steps:
1. `emacs -q`
2. Load centaur tabs and dependencies
3. `M-x centar-tabs-mode`
All is fine thus far.
4. `(setq centaur-tabs-close-button nil)`
5. `M-x centar-tabs-mode` (disable centaur tabs)
6. `M-x centar-tabs-mode` (re-enable centaur tabs)
Tab bar is there but has no tabs.

**Comment by ema2159** [comment]
You should be doing `(setq centaur-tabs-set-close-button nil)` instead of `(setq centaur-tabs-close-button nil)`. I think that's the problem

**Comment by joca-bt** [comment]
Thanks, I missed the `set` in the middle.
