### ISSUE TITLE
Tab unselected and headerline background are different

### ISSUE THREAD

**Issue by Compro-Prasad** [ema2159/centaur-tabs#43]
I am using `slant` tab separator.
![Screenshot from 2019-08-07 08-04-19](https://user-images.githubusercontent.com/11143962/62590647-a9ac2500-b8ea-11e9-83f5-90b3973a0993.png)

**Comment by Compro-Prasad** [comment]
In the above  screenshot, the background of slant separator doesn't match with the rest of the header line.

**Comment by ema2159** [comment]
Are you using the `(centaur-tabs-headline-match)` function?

**Comment by Compro-Prasad** [comment]
No. Thanks I just fixed it. IMO it should go into `centaur-tabs-buffer-init` function.

**Comment by ema2159** [comment]
I've also thought that. The thing is that it overrides the headerline-face which is external to my package but also if somebody is using centaur tabs it is unlikely they be using the headerline for something else.

**Comment by tranxuanthang** [comment]
What did I do wrong? It only works after I run it with "eval-expression" (mine is `SPC ;` `(centaur-tabs-headline-match)`). I'm using doom-emacs distribution.

```elisp
(def-package! centaur-tabs
  :demand
  :config
  (setq centaur-tabs-style "wave")
  (setq centaur-tabs-set-bar 'over)
  (setq centaur-tabs-height 32)
  (setq centaur-tabs-set-modified-marker t)
  (centaur-tabs-enable-buffer-reordering)
  (centaur-tabs-group-by-projectile-project)
  ;; (centaur-tabs-inherit-tabbar-faces)
  (centaur-tabs-headline-match)
  (centaur-tabs-mode t)
  )
```
![Screenshot_2019-08-07_15-03-08](https://user-images.githubusercontent.com/15942946/62608142-805eb980-b929-11e9-9dbc-8d0173c0d9a5.png)

**Comment by Compro-Prasad** [comment]
Replace:
```
  (centaur-tabs-headline-match)
  (centaur-tabs-mode t)
```
with:
```
  (centaur-tabs-mode t)
  (centaur-tabs-headline-match)
```

**Comment by ema2159** [comment]
Also take into account you're on Doom's dashboard which may blend the headerline and unselected tabs with the buffer, so better check it in a file visiting buffer

**Comment by tranxuanthang** [comment]
@Compro-Prasad @ema2159 
Thank you, I'm still new to emacs & elisp and I'm very happy I got some responses here. I tried switching the order of `(centaur-tabs-mode t)` and `(centaur-tabs-headline-match)` but it was still the same as before. Now I end up doing something like this in config.el:

```elisp
(defun setup-centaur-tabs()
  (setq centaur-tabs-style "wave")
  ;; (setq centaur-tabs-set-bar 'over)
  (setq centaur-tabs-height 32)
  (setq centaur-tabs-set-modified-marker t)
  (centaur-tabs-enable-buffer-reordering)
  (centaur-tabs-group-by-projectile-project)
  (centaur-tabs-headline-match)
  (centaur-tabs-mode t)
  )

(after! ivy
  (def-package! centaur-tabs
    :config
    (setup-centaur-tabs)
    )
  )
```
I still don't know why, but if load the package after doom's ivy module with doom's `after!` function, it works, though it makes the tabbar appears a little later after emacs loaded. Unselected tabs and headerline do blend with Doom dashboard's background, but it's acceptable for me for now.

![image](https://user-images.githubusercontent.com/15942946/62631756-73f35480-b95b-11e9-9190-4a163dd47bda.png)

**Comment by ema2159** [comment]
No worries man, we've all been there. Could you try an `(after! doom-themes`?

**Comment by tranxuanthang** [comment]
@ema2159 I'm still trying different names but replacing `ivy` with `doom-themes` doesn't work. Most of package names don't work (centaur-tabs loads but headline color doesn't match), it must be things that take a long time to start, or start manually, like magit or treemacs.

**Comment by ema2159** [comment]
Yes, maybe it should load not only after doom themes but also the theme itself. :defer 0 is a good option though so go for it! Also in your config you could add hooks to `centaur-tabs-local-mode` to buffers like dashboard, so the tabs hide in buffers that are better without tabs!
