### ISSUE TITLE
second click on tab changes tabbar background color (Solaire Mode)

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#47]
Note the bg color:
![Screenshot from 2019-08-13 09-47-56](https://user-images.githubusercontent.com/19470159/62920937-d612e600-bdaf-11e9-8153-9ac80bbf327e.png)

I'm clicking `*Messages*`. Note that bg is lighter now:
![Screenshot from 2019-08-13 09-48-15](https://user-images.githubusercontent.com/19470159/62920942-da3f0380-bdaf-11e9-9b63-d676e2881743.png)

I'm clicking `*Messages*` again. Bg restored to previous state
![Screenshot from 2019-08-13 09-48-03](https://user-images.githubusercontent.com/19470159/62920946-e034e480-bdaf-11e9-9276-20f874d64f4d.png)

If I unfocus Emacs this doesn't happen unless I do consecutive switching between tabs again.

My Centaur tabs config:
https://github.com/andreyorst/dotfiles/blob/dff3996e17a8c70e0e502bdf6d90cff668447536/.emacs.d/init.el#L532-L561

My DOOM Themes config:
https://github.com/andreyorst/dotfiles/blob/dff3996e17a8c70e0e502bdf6d90cff668447536/.emacs.d/init.el#L157-L163

My [Solaire Mode](https://github.com/hlissner/emacs-solaire-mode) config:
https://github.com/andreyorst/dotfiles/blob/dff3996e17a8c70e0e502bdf6d90cff668447536/.emacs.d/init.el#L176-L215

Without Solaire there's no bug. Happens with all DOOM Themes for me. Seems like `(solaire-mode-swap-bg)` is causing the problem

**Comment by ema2159** [comment]
Yes, I'm aware of this. I also use solaire mode. I have to speak with Henrik to see if I can switch centaur tabs selected and unselected colors in non file visiting buffers

**Comment by ema2159** [comment]
You should also open an issue in `solaire-mode` repo, there's nothing I can do to solve this here
