### ISSUE TITLE
all tabs in one group possible?

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#48]
Is it possible to display all tabs from different directories/projects in one group? I'm not using projectile, and have a custom function for `project.el` to find roots, but I mainly use it for eglot.

if I'm working on file on a different project it creates new group for it which I don't like, because this hides all other tabs. Switching groups is just an additional action for me and I would like to avoid it until it's really necessary.

Related: #15

**Comment by andreyorst** [comment]
Oh. Never-mind, I've figured it out :)

**Comment by Xunius** [comment]
@andreyorst can you share your solution?

**Comment by andreyorst** [comment]
https://github.com/andreyorst/dotfiles/commit/433a2f31ab4a476ca26ea57932d46caa772d83d0
