### ISSUE TITLE
Button/ability to kill window?

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#51]
Sometimes when I close a buffer in a multi-window setup I also want to kill that window. If I'm doing it on a keyboard it's easy as `C-x k RET C-x 0`. But when I'm interacting with mouse by using tabs, there's a way to kill a buffer with the close button, but no way to kill the window with the tabline. Maybe it is good idea to add a button that will kill the window?

Or as another solution the window can be killed if there's no tabs left in the group, so instead of switching the active group, the window will be killed automatically, like in Atom? Though this may involve having separate groups for separate windows.

**Comment by andreyorst** [comment]
Also another feature from Atom, and another editors with tabs as central way to manage opened buffers:

If a tab presented in two windows the file is not closed until all tabs are. E.g. (`!` are window separators):

```
```

Pressing `x` on `some-file` tab in `window 2` results in closing `window 2` and not closing the buffer of `some-file`

```
! | some-file x |                   !
!                                   !
!                                   !
!                                   !
!                                   !
```

If there are several different buffers in those windows:

```
! | some-file x | ! | some-file x | | other-file x | !
!                 !                                  !
!                 !                                  !
!       window 1  !  window 2                        !
!                 !                                  !
```

```
! | some-file x | ! | other-file x | !
!                 !                  !
!                 !                  !
!       window 1  !  window 2        !
!                 !                  !

This will make it easier to manage windows with mouse

**Comment by Compro-Prasad** [comment]
This is not possible with the current implementation of tabs because:
1. Buffers are tabs.
2. Groups are not tied to windows.
3. Groups are managed automatically.
4. You cannot assign buffers to specific groups manually.

This can be done using `window-parameter`. But that will need a different implementation for this specific feature.

**Comment by ema2159** [comment]
@Compro-Prasad is right, given the current implementation this feature is a little bit hard to implement given the way that buffer groups are managed

**Comment by andreyorst** [comment]
I close this, since I've described the idea in a more clear way (I hope) in #61
