### ISSUE TITLE
Disabling `centaur-tabs-mode` breaks Emacs

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#56]
Reproduce steps:

1. Launch Emacs like this:
   ```
   emacs -q --eval "(progn (package-initialize) (require 'centaur-tabs))"
   ```
2. `M-x centaur-tabs-mode RET`
   Tabs should appear
3. `M-x centaur-tabs-mode RET`
   Tabs should disappear
4. Try to exit Emacs with`C-x C-c` or the close button, or change buffer, or call `M-x`

Every action prints this error message in my case:
```
funcall: Symbol’s value as variable is void: pl/reverse-pattern
```
Without `Emacs -q` the message is different:
```
funcall: Symbol’s value as variable is void: gnus-widget-reversible-match
```
and seems that it depends on the configuration and quite random.

I'm using 

    GNU Emacs 26.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.8) of 2019-04-30
    GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29

**Comment by ema2159** [comment]
This one is a little bit odd, I'll have to give it a closer look
