### ISSUE TITLE
*Minibuf-1* started to appear with other buffers

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#57]
I'm using this function to create groups:

```emacs-lisp
(defun centaur-tabs-buffer-groups ()
  "Use as few groups as possible."
  (list (cond ((string-equal "*" (substring (buffer-name) 0 1))
               (cond ((string-match-p "eglot" (buffer-name)) "Eglot")
                     ((or (string-match-p "geiser" (buffer-name))
                          (string-match-p "repl \\*" (buffer-name))) "Geiser")
                     (t "Tools")))
              ((string-match-p "magit" (buffer-name)) "Magit")
              (t "Default"))))
```
Whenever I open `M-x` or using `phi-search` this tab appears:
![image](https://user-images.githubusercontent.com/19470159/64518745-726ed080-d2fb-11e9-9a3e-8904e778f0c4.png)

But only in single window:
![image](https://user-images.githubusercontent.com/19470159/64522095-eca25380-d301-11e9-9346-cb4d7ba8408a.png)

I thought that first `cond` branch should put this buffer into the `"Tools"` group, but it seems that with latest updates, that brought multiple buffers in multiple groups I need to handle this thing differently?

**Comment by ema2159** [comment]
I'm aware of this one, in fact it's easy to solve however I've been quite busy recently so I've been unable to fix it.

**Comment by Compro-Prasad** [comment]
This can be solved 2 ways:
1. The best way is to make your group function robust.
2. The PR that I made, always updates groups when a new buffer is created which is definitely a good thing but also includes temporary buffers. Somehow I need to be able to detect if its a temporary buffer and skip updating the groups. This way it will also become a bit less resource hungry while updating the groups.

If both of the above are fixed this wont appear again.

**Comment by andreyorst** [comment]
> The best way is to make your group function robust.

What should I improve?

**Comment by Compro-Prasad** [comment]
I use [this](https://github.com/Compro-Prasad/emacs-config/blob/master/init.el#L862) group function.

**Comment by andreyorst** [comment]
> I use [this](https://github.com/Compro-Prasad/emacs-config/blob/master/init.el#L862) group function. It might be having some edge cases but I don't usually see this issue.

Actually you don't need `(let*` in [this line](https://github.com/Compro-Prasad/emacs-config/blob/e96c3fdb05199b2ef0e440ed9a47912ead5137fd/init.el#L863), since all bindings are not relying on eachother, so `(let` should do. Also I noticed, that instead of returning result of the `(cond` into `(list` you manually do list quoting with `'()`. Why? Other than that I see no differences in the logic, besides that you check for some `major-mode`s and I don't, but in case of `*Minibuf-1*` the `major-mode` is set to `minibuffer-inactive-mode`, which isn't handled in your function as well.

I also noticed that I do not experience the issue on Emacs 26.2, only on Emacs 26.3.

**Comment by Compro-Prasad** [comment]
Thanks for reviewing my code. I will improve it soon.

**Comment by andreyorst** [comment]
The issue no longer appears on my work PC, however I did not changed anything in configuration since yesterday.

**Comment by ema2159** [comment]
I found one possible cause for this error. The minibuffer name is not "*Minibuf-1", but it's rather " *Minibuf-1" (notice the space before the *). So, when checking for the buffer name to exclude it you shall use for example (string-prefix-p " *Mini"...). I'll solve it on the next commit
