### ISSUE TITLE
no tabs when opeing file from treemacs buffer or via command line

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#58]
steps to reproduce:
```
emacs -q --eval "(progn
                   (package-initialize)
                   (require 'centaur-tabs)
                   (require 'treemacs)
                   (treemacs)
                   (centaur-tabs-mode t))" test_file
```
**Outcome**:
![image](https://user-images.githubusercontent.com/19470159/64524541-64bf4800-d307-11e9-9287-5e9b56975b18.png)

**Expected**:
![image](https://user-images.githubusercontent.com/19470159/64524574-79034500-d307-11e9-8b3b-c8a4231c5464.png)

removing `(treemacs)` call makes tabs appear at launch.

Also can be observed with these steps:
1. launch Emacs like so:
   ```
   emacs -q --eval "(progn
                      (package-initialize)
                      (require 'centaur-tabs)
                      (require 'treemacs)
                      (treemacs)
                      (centaur-tabs-mode t))"
   ```
   (also observe that tabline is empty for `*messages*` and `*scratch*` buffers until first click)
2. While cursor is inside `treemacs` window press `C-x C-f test_file RET`

**Outcome**: No tabs in new buffer
**Expected**: Tabs in `test_file` buffer.

Happens on

    GNU Emacs 26.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.8) of 2019-04-30
    GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29

**Comment by Compro-Prasad** [comment]
Instead of:
```
(treemacs)
(centaur-tabs-mode t)
```
do:
```
(centaur-tabs-mode t)
(treemacs)
```

**Comment by andreyorst** [comment]
This doesn't fix the issue with opening files while treemacs window is focused

**Comment by simurgh9** [comment]
I have the same problem.

**Comment by simurgh9** [comment]
@andreyorst Did you figure out a work around?

**Comment by andreyorst** [comment]
@simurgh9 no, I've switched to Emacs 27 and using builtin tabs right now.
