### ISSUE TITLE
[Suggest] icon colors

### ISSUE THREAD

**Issue by seagle0128** [ema2159/centaur-tabs#6]
It's better make the color of the buffer icons on inactive tabs "gray" (same as the buffer names). This can be a customization for users.

**Comment by ema2159** [comment]
Hello Mr. Zhang, I had already thought of this feature, but I didn't knew if it was something users would want, although now I see it is. I'll implement it as soon as possible although I'm a little busy trying to get this on MELPA (it is much harder than I thought!), so a PR is welcome!

**Comment by ema2159** [comment]
Mr. Zhang, do you have any idea how to do this? All the icons is a real pain jaja

**Comment by seagle0128** [comment]
> Mr. Zhang, do you have any idea how to do this? All the icons is a real pain jaja

@ema2159  Just set `mode-line-inactive` face to the icon, e.g.

```elisp
(propertize icon 'face `(:inherit ,(get-text-property 0 'face icon)
                         :inherit mode-line-inactive))
```

**Comment by ema2159** [comment]
> @ema2159
> 
> treemacs-icons-dired.el doesn't seem to be using all-the-icons.el, so it may worth taking a look at it:
> 
> * https://github.com/Alexander-Miller/treemacs/blob/master/src/extra/treemacs-icons-dired.el
> * https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-icons.el

Hmmm, I may give it a look. I've used the package before

**Comment by ema2159** [comment]
> > Mr. Zhang, do you have any idea how to do this? All the icons is a real pain jaja
> 
> @ema2159 Just set `mode-line-inactive` face to the icon, e.g.
> 
> ```emacs-lisp
> ;; or add-face-text-property, remove-text-properties
> (propertize icon 'face `(:inherit ,(get-text-property 0 'face icon)
>                          :inherit mode-line-inactive))
> ```

Ok, I'll try that! Just one thing, you were talking about graying out the unselected tabs, or graying out the tabs of an unactive window (I think he latter is the better option).

**Comment by seagle0128** [comment]
@ema2159 I think so, but some people may like the other one. So the best solution is to add an option of different styles: display colorful icons, display white icons, graying out the unselected tabs, graying out the tabs of an unactive window, or not displaying icons, etc.

**Comment by ema2159** [comment]
Thanks Mr. Zhang! This functionality is now implemented, and your snippet also helped me to set the background of the icon in a much better way than it was before. The icon gray out is only implemented for unselected buffers, the unselected windows option is pending.

**Comment by seagle0128** [comment]
Great job! Thank you, @ema2159 .
