### ISSUE TITLE
[discussion] Buffer-Tab relationship semantics

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#61]
I had thought about relationship between buffers and tabs, and came to the conclusion, that buffer != tab. Or at least the relationship is not 1 to 1.

In Emacs, everything we interact with is a buffer. Buffer is a data structure that can hold anything, but primarily holds text information. It may seem natural to tie tabs to buffers as 1 to 1 relationship, but after giving it some thought, I've realized, that tabs are not meant to be buffers. Tabs are interface to interact with meaningful set of buffers that can be manged from graphical interface. Current grouping semantics are more a hack over the problem of *not displaying* tabs for buffers that we not need to see. Therefore I think that relationship between buffers and tabs should not be as tight. Tabs are merely a graphical interface, while buffers are data structure, so I think this can be changed to work like in other GUI editors out there.

I've thought about some set of rules on how we can manage tabs, and here's what I've got:

1. Buffer can have as many tabs as long as these conditions are true:
   1. Buffer is not marked as `ignored`
   2. Buffer can have only 1 tab per window.
2. Buffer can exist without tab, but tab can not exist without buffer. Therefore such buffer killing semantics apply:
   1. Buffer that do not have tabs cannot be killed by tab plugin. `ignored` buffers must be managed by existing Emacs functions.
   2. Buffer that has more than 1 tab cannot be killed by tab plugin.
   3. Closing tab must kill buffer if there is no other tabs of this buffer exist.
3. Window can have as many tabs as long as these conditions are true:
   1. Window is not displaying `ignored` buffer;
   2. Window is not marked as `dedicated`;
4. Window can exist without tabs, but tabs can not exist without
   window. Therefore such window killing semantics apply:
   1. Window that has more than 1 tab cannot be killed by tab plugin;
   2. Closing tab must kill window if there is no other tabs left in the window;
   3. Window that has no tabs cannot be killed by tab plugin.
   4. Manually killing window must transfer all of its tabs to another window.
   5. Window that no longer applies to conditions mentioned in **3.** automatically transfers its tabs to another window. (E.g. making window dedicated to a buffer, or switching to `ignored` buffer disables tabs for current window.)

So in implementation could be as a some sort of a tree structure that holds buffer name and its properties. For example, a json structure:

``` json
{
    "buffers": [
        {
            "id": "buffer-id",
            "ignored": false,
            "tabs": [
                {
                    "window": {
                        "id": "window-id",
                        "dedicated": false
                    }
                },
                {
                    "window": {
                        "id": "window-id",
                        "dedicated": false
                    }
                }
            ]
        },
        {
            "id": "buffer-id",
            "ignored": true,
            "tabs": []
        },
    ]
}
```

So the thing is that if some buffer `Buffer1` exists and doesn't marked as `ignored` a tab should be displayed in a `#<window A on Buffer1>` where the buffer is displayed. Currently centaur-tabs works like this. If we have `Buffer1` displayed in secondary window `#<window B on Buffer1>` a tab should be displayed in both windows now. Again, centaur-tabs works the same. Now if we try to close a tab in `#<window B on Buffer1>`, a rule number **2.ii** evaluates. Since buffer has 2 tabs both in `#<window A on Buffer1>` and `#<window B on Buffer1>` it cannot be killed. So the tab is being killed. After that a windowing rule **4.ii** must be evaluated. Since `#<window B on Buffer1>` has no tabs to display it must be deleted, so only one window `#<window A on Buffer1>` with `Buffer1` tab is displayed. The data structure above doesn't include information about window in `buffer` field itself because the data structure should inspected only after window is tested for `dedicated`. Yet the information about some window displaying a `dedicated` buffer that has other tabs somewhere in other windows can be handy.

The other rules can be applied to situations when we display several tabs and make window `dedicated` in the same way as described in previous paragraph. I believe this will bring more consistent tab interface to Emacs which represents real tabs in GUI editors and other tab based environments. I want to hear your thought on these approaches.

**Comment by andreyorst** [comment]
[Today native tabs are landed in Emacs git](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=2698d3dba2e9858b026ed127d4de3f86810a5ef3). And these aren't tabs, but window configurations. E.g. it works like *browser tabs*, and not tabs like in text editor. That's how it looks right now:

![image](https://user-images.githubusercontent.com/19470159/66144877-53b9dc00-e612-11e9-91e7-9f2eccf6cd52.png)

Thre's some errors in `*Messages*` buffer, about missing icons, but I think that missing visuals can be predicted.

Since native tabs are not tabs, that Centaur Tabs try to provide, I hope that this plugin will still be worked on.

**Comment by andreyorst** [comment]
I've adopted this pattern for Emacs 27 buit-in tabs. The code can be found here:

https://github.com/andreyorst/dotfiles/blob/7824f68756e5fff4c638c522f2fed75cf2bda0bc/.emacs.d/init.el#L690-L718

**Comment by ema2159** [comment]
This will very likely be implemented when Emacs 27 gets released and I start supporting the built-in tabs, by using Emacs 27's tab and group managing as the logic and just dedicating this package to the aesthetic part of the tabs. I think Emacs 27 will be released soon. Please let me know when this happens so that I can start working on that.
