### ISSUE TITLE
Problems with "Init adds all hooks. Disable removes all hooks." commit

### ISSUE THREAD

**Issue by djangoliv** [ema2159/centaur-tabs#62]
Since the commit: 
https://github.com/ema2159/centaur-tabs/commit/90220c26cbc77b121eeb065e30f6d7a395ef131f

The functions `centaur-tabs-hide-tab` and `centaur-tabs-buffer-groups` are no longer taken into account.

Regards

**Comment by ema2159** [comment]
Sorry! I've been unable to work on this because I'm changing my job. Could you be a little more descriptive with the problem, like with an example?

**Comment by djangoliv** [comment]
No problem. Since the last commit, all buffers are visible (even those who are referenced in `centaur-tabs-hide-tab`). however, the groups seem to be respected.

i.e. this function is not taken into account :
```
(defun centaur-tabs-hide-tab (x)
    (let ((name (format "%s" x)))
      (or
       (string-prefix-p "*" name)
       (and (string-prefix-p "magit" name)
            (not (file-name-extension name)))
       )))
```

**Comment by Compro-Prasad** [comment]
For me it is working: https://github.com/Compro-Prasad/emacs-config/blob/b08b2aa644d08e5a9a1bef82c1f9a15ae197b1d8/init.el#L840

**Comment by djangoliv** [comment]
I tried with this init.el file: emacs -q -l init.el

```
(add-to-list 'load-path "~/.emacs.d/centaur-tabs")
(add-to-list 'load-path "~/.emacs.d/powerline/")
(require 'centaur-tabs)
(centaur-tabs-mode t)
(defun centaur-tabs-hide-tab (x)
  "Do no to show buffer X in tabs."
  (let ((name (format "%s" x)))
    (and
     (not
      (or
       ;; Whitelist - Will not be hidden
       (string-equal "*Messages*" name)
       (string-equal "*scratch*" name)
       (string-equal "*Help*" name)
       (string-prefix-p "*eww" name)
       (string-prefix-p "*terminal" name)))
     (or
      ;; Current window is not dedicated window.
      (window-dedicated-p (selected-window))
      ;; Is not magit buffer.
      (and (string-prefix-p "magit" name)
           (not (file-name-extension name)))
      ))))
```

I open current directory in emacs:  `emacs -q -l init.el . `
and I get a group of tabs containing the buffers: *Messages*, *Scratch*, *Gnu Emacs*

![centaur](https://user-images.githubusercontent.com/13416971/66394146-942fa600-e9d4-11e9-92f2-68b352a6d3b8.png)

**Comment by Compro-Prasad** [comment]
@djangoliv What was the expected outcome?

**Comment by djangoliv** [comment]
@Compro-Prasad Ideally, I'd like the internal buffers (*Message*, *scratch* ... and magit buffers) to be hidden (do not belong to any group of tabs).

Before commit 90220c2 with the code below this kind of buffers did not have tabs, Now yes.

```
(defun centaur-tabs-hide-tab (x)
    (let ((name (format "%s" x)))
      (or
       (string-prefix-p "*" name)
       (and (string-prefix-p "magit" name)
            (not (file-name-extension name)))
       )))
```

Th question is: how can i get the internal buffers ignored by centaur tabs ?

**Comment by Compro-Prasad** [comment]
I  tweaked my config to suit your needs:
```elisp
  (defun compro/centaur-tabs-hide-tab (x)
    "Do no to show buffer X in tabs."
    (let ((name (format "%s" x)))
      (and
       (not
        (or
         ;; Whitelist - Will not be hidden
         ))
       (or
        ;; Current window is not dedicated window.
        (window-dedicated-p (selected-window))

        ;; Blacklist - Will be hidden
        (string-prefix-p "*" name)
        (and (string-prefix-p "magit" name)
             (not (file-name-extension name)))
        ))))
```

**Comment by ema2159** [comment]
No, there's actually an issue, the customized function is not being loaded for some reason so whatever you're trying to hide from your configuration won't take effect. I'll come here with a solution soon.

**Comment by ema2159** [comment]
The problem is a little bit odd. It seems that the function actually works but the Messages and scratch buffers load before that function and somehow remain cached in the groups. I'll keep on searching a solution

**Comment by djangoliv** [comment]
Thank you for working on this @ema2159.
