### ISSUE TITLE
Change centaur-tabs-default :background color

### ISSUE THREAD

**Issue by fabiotatsuo** [ema2159/centaur-tabs#64]
Hi all,

First thanks to ema2159 for sharing and working with centaur-tabs.

I am new to emacs, trying to customize tab background color but I am failing. Can anyone help me?

The part I am trying to change is the tab background color (black). I want it white.

<img width="995" alt="Screen Shot 2019-10-01 at 9 20 54 PM" src="https://user-images.githubusercontent.com/4140114/66010077-cc465e80-e493-11e9-8435-0f69b6d117a4.png">

Here is my config. bg1 is #ffffff and bg2 is #f0f0f7

```
;; Centaur-tabs
               (centaur-tabs-default :background ,bg1 :foreground ,black1 :box nil)
               (centaur-tabs-selected :background ,bg1 :foreground ,black1 :box nil)
               (centaur-tabs-unselected :background ,bg2 :foreground ,black2 :box nil)
               (centaur-tabs-selected-modified :background ,bg1 :foreground ,orange1 :box nil)
               (centaur-tabs-unselected-modified :background ,bg2 :foreground ,orange1 :box nil)
               (centaur-tabs-active-bar-face :background ,yellow1 :box nil)
               (centaur-tabs-modified-marker-selected :inherit 'centaur-tabs-selected-modified :foreground ,yellow1 :box nil)
               (centaur-tabs-modified-marker-unselected :inherit 'centaur-tabs-unselected-modified :foreground ,yellow1 :box nil)
```

I think is it same case on minimap window.

<img width="1017" alt="Screen Shot 2019-10-01 at 9 09 51 PM" src="https://user-images.githubusercontent.com/4140114/66010127-0ca5dc80-e494-11e9-825a-1c4fe5dac3ae.png">

Thanks

**Comment by ema2159** [comment]
Hi! Sorry, I've been unable to work on centaur-tabs for some time giving I'm changing my job. For doing what you want you need two things:

1 - Use the `(centaur-tabs-headline-match)` function in your config

2 - Customize the plugin faces (which you've already done)

So, pasting `(centaur-tabs-headline-match)` after your current configuration should do it. I also encourage you to use either doom-themes or kaolin-themes, which already have support for centaur-tabs.

**Comment by fabiotatsuo** [comment]
Hi ema2159,

I understand and thanks for your reply.

I have `(centaur-tabs-headline-match)` on my `init-centaur-tabs.el`. I am using your personal configuration that I found on README.md.

```
;; Centaur tabs
(use-package centaur-tabs
  ; :demand
  :config
  (setq centaur-tabs-style "bar"
        centaur-tabs-height 22
        centaur-tabs-set-icons t
        centaur-tabs-set-modified-marker t
        centaur-tabs-set-bar 'left)
  (centaur-tabs-headline-match)
  ;; (setq centaur-tabs-gray-out-icons 'buffer)
  ;; (centaur-tabs-enable-buffer-reordering)
  ;; (setq centaur-tabs-adjust-buffer-order t)
  (centaur-tabs-mode t)
  (setq uniquify-separator "/")
  (setq uniquify-buffer-name-style 'forward)
  (defun centaur-tabs-buffer-groups ()
    "`centaur-tabs-buffer-groups' control buffers' group rules.

    Group centaur-tabs with mode if buffer is derived from `eshell-mode' `emacs-lisp-mode' `dired-mode' `org-mode' `magit-mode'.
    All buffer name start with * will group to \"Emacs\".
    Other buffer group by `centaur-tabs-get-group-name' with project name."
    (list
      (cond
        ((or (string-equal "*" (substring (buffer-name) 0 1))
 	      (memq major-mode '(magit-process-mode
				 magit-status-mode
				 magit-diff-mode
				 magit-log-mode
				 magit-file-mode
				 magit-blob-mode
				 magit-blame-mode
				 )))
	 "Emacs")
	((derived-mode-p 'prog-mode)
	 "Editing")
	((derived-mode-p 'dired-mode)
	 "Dired")
	((memq major-mode '(helpful-mode
			     help-mode))
	 "Help")
	((memq major-mode '(org-mode
			     org-agenda-clockreport-mode
			     org-src-mode
			     org-agenda-mode
			     org-beamer-mode
			     org-indent-mode
			     org-bullets-mode
			     org-cdlatex-mode
			     org-agenda-log-mode
			     diary-mode))
	 "OrgMode")
	(t
	(centaur-tabs-get-group-name (current-buffer))))))
  :hook
  (calendar-mode . centaur-tabs-local-mode)
  (dashboard-mode . centaur-tabs-local-mode)
  (helpful-mode . centaur-tabs-local-mode)
  (imenu-list-minor-mode . centaur-tabs-local-mode)
  (org-agenda-mode . centaur-tabs-local-mode)
  (minimap-mode . centaur-tabs-local-mode)
  (term-mode . centaur-tabs-local-mode)
  :bind
  ("C-<prior>" . centaur-tabs-backward)
  ("C-<next>" . centaur-tabs-forward)
  ("C-c t s" . centaur-tabs-counsel-switch-group)
  ("C-c t p" . centaur-tabs-group-by-projectile-project)
  ("C-c t g" . centaur-tabs-group-buffer-groups))
  ;(:map evil-normal-state-map
  ;  ("g t" . centaur-tabs-forward)
  ;  ("g T" . centaur-tabs-backward)))


(provide 'init-centaur-tabs)
```

I will check doom and kaolin themes to try discover where I am failing.

Thanks

**Comment by fabiotatsuo** [comment]
Fix it... just will post to maybe help another and closing it.

I checked the other themes and saw that they put same color for `(centaur-tabs-default :background ,bg1 :foreground ,bg1)` but still not working. Since I doing new custom color theme and have only few variables on my theme yet, I need to change `(header-line :background ,bg1)`.

<img width="998" alt="Screen Shot 2019-10-02 at 2 26 54 AM" src="https://user-images.githubusercontent.com/4140114/66020062-3246dc00-e4bc-11e9-8f76-80d03d3cfbe5.png">

Thanks again.

`
