### ISSUE TITLE
Emacs 27 native `tab-line`

### ISSUE THREAD

**Issue by andreyorst** [ema2159/centaur-tabs#66]
[Now Emacs 27 ships native tabs](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=2698d3dba2e9858b026ed127d4de3f86810a5ef3):

![image](https://user-images.githubusercontent.com/19470159/66320626-df3faf80-e927-11e9-9cf9-26db7c7f00f4.png)

And has new `tab-line` which is similar to `header-line`, but used for tabs. I wonder if Centaur Tabs could use this in its advance to provide tabs without using `header-line` if this feature is present.

**Comment by Compro-Prasad** [comment]
Thanks for the work on customizing the tab line.

**Comment by ema2159** [comment]
Hi Andrey! I would definitely do this with the new tab-line and tab-bar. I think it's a little bit early though, given that this features are still under development.
