### ISSUE TITLE
Error in byte complie: Symbol's function definition is void: centaur-tabs-separator-pattern-defun

### ISSUE THREAD

**Issue by alearaher** [ema2159/centaur-tabs#7]
Tried byte-compiling the package on MacOS 10.14.4  with emacs version 26.1  and this error pop's up. This does not allow the creation of the .elc file and as such the package cannot be loaded.

**Comment by thermopyle** [comment]
I experience the same problem.

**Comment by ema2159** [comment]
I'm aware of this one, it's a major problem and I need to fix it as soon as possible. It is a problem of those being centaur-tabs-separator... being macros instead of functions, if you find a solution please submit a PR.



> Tried byte-compiling the package on MacOS 10.14.4 with emacs version 26.1 and this error pop's up. This does not allow the creation of the .elc file and as such the package cannot be loaded.

Holi Ale

**Comment by ema2159** [comment]
Fixed! Tell me if now thing work alright.

**Comment by thermopyle** [comment]
After the update, when byte-compiling I get this error instead;

`centaur-tabs.el:45:1:Error: Cannot open load file: No such file or directory, powerline`

**Comment by ema2159** [comment]
You must have powerline installed. When this get in MELPA those dependencies will be resolved automatically
