### ISSUE TITLE
Weird close icon?

### ISSUE THREAD

**Issue by DakshMiglani** [ema2159/centaur-tabs#76]
Whenever I edit the file, the close icon changes to:

![image](https://user-images.githubusercontent.com/23355449/68020697-4bae9400-fcc5-11e9-8871-d71ee360afd8.png)

I'm guessing this is a font issue, and I've tried installing `all-the-icons-install-fonts` but still it doesn't seem to work.

**Comment by ema2159** [comment]
That's odd. All the icons is not the problem. I use an unicode bullet icon for the modified marker. Could you try to change the modified marker? Do `(setq centaur-tabs-modified-marker "*")` in your config and see if it displays the asterisk correctly.

**Comment by DakshMiglani** [comment]
Yes that fixes it! Thanks a lot!
