### ISSUE TITLE
About customize the close button

### ISSUE THREAD

**Issue by tnira** [ema2159/centaur-tabs#77]
Is it possible to set the close button to be displayed on the left side of the tab?

**Comment by tnira** [comment]
Thank you for the reply.

I understand that in many user interfaces, the close box nests to the right.
However, the Mac file manager and browser tab close boxes are on the left.
In my search, I couldn't find a product with a tab close box on the left side in a text editor.
If the close box is right or left, the mouse operation will be lost for a moment. So, I used Emacs which does not have a tab function by default.
I recently discovered "centaur-tabs" and thought it would be great if I could change the position of the closebox.

**Comment by ema2159** [comment]
I could try to implement this feature. I'll let you know when it' done

**Comment by ema2159** [comment]
Hi @tnira! Hope you're doing fine. I just added the requested feature. Please use it and tell me if it's alright (i.e. if you like it aesthetically, if it is what you expected etc)

**Comment by tnira** [comment]
@ema2159 Thank you for function implementation!
This is exactly what I expected.
