### ISSUE TITLE
tabbar-buffer-list-function equivalent

### ISSUE THREAD

**Issue by djangoliv** [ema2159/centaur-tabs#8]
1: Thanks for this package \o/

2: 
Is there an equivalent to the variable tabbar-buffer-list-function ?
I would like to exclude some buffers by their name:

example in tabber to exclude internal, magit and TAGS buffers:

```
(setq tabbar-buffer-list-function
       (lambda ()
           (remove-if
            (lambda(buffer)
              (or (string-match-p "TAGS" (buffer-name buffer))
                  (string-match-p "^magit.*" (buffer-name buffer))
                  (find (aref (buffer-name buffer) 0) " *" )))
            (buffer-list))))

```

Regards

**Comment by ema2159** [comment]
Yes sir there is. Sorry, I forgot to document it. I just added it in the README and tell me if it's alright. If it isn't, reopen the issue.

**Comment by djangoliv** [comment]
Perfect \o/
