### ISSUE TITLE
Weird display of the modified marker and icons are not displayed

### ISSUE THREAD

**Issue by fperies** [ema2159/centaur-tabs#80]
Hello,

I work on a RHEL7 machine and with Spacemacs.
After having done the installation and set the following configuration, I get the strange display below when a buffer gets modified (little box with 23FA inside!):

`dotspacemacs-additional-packages '(all-the-icons buffer-move centaur-tabs)`
```
(setq centaur-tabs-set-icons t
         centaur-tabs-style "wave"
         centaur-tabs-set-bar 'under
         centaur-tabs-set-modified-marker "*"
         centaur-tabs-cycle-scope 'tabs)
```

![image](https://user-images.githubusercontent.com/7024137/69442305-a1b6aa80-0d4c-11ea-8f52-e58aca096763.png)

Also, as you can see, the icons are not displayed while variable  centaur-tabs-set-icons is set.

Do you happen to know why I hit such issues ?
Thanks
Regards

**Comment by ema2159** [comment]
Have you installed all-the-icons's fonts?

**Comment by fperies** [comment]
No, I haven't.
I thought that was the purpose of the spacemacs-additional-packages statement (all-the-icons).
Do you mean there is something more to do ? If yes, what exactly ?

**Comment by ema2159** [comment]
In vanilla Emacs you have to run the `all-the-icons-install-fonts` command to install the necessary fonts to display the icons. I don't have any experience with Spacemacs though. Maybe @levindu can help you, he uses the package with Spacemacs if I'm not wrong.

**Comment by levindu** [comment]
@fperies 

try following:
```
    (setq
     centaur-tabs-set-close-button t
          centaur-tabs-style "wave"
          centaur-tabs-set-bar 'under
          centaur-tabs-set-modified-marker t
          centaur-tabs-modified-marker "*"
          centaur-tabs-cycle-scope 'tabs)
```

which uses '*' instead of the unicode char to display the modifying state.

And you should install some unicode fonts for correctly display of unicode char, such as the default one of:

```
;; (make-string 1 #x23FA)
"⏺"
```

**Comment by fperies** [comment]
@levindu 
I already use "*" as marker for modified buffer.
I've run the M-x all-the-icons-install-fonts and now I get the following display with thos strange characters instead of icons:
![image](https://user-images.githubusercontent.com/7024137/69530257-09017400-0f72-11ea-89f3-cd290ba52642.png)
On the other hand, I've checked I have unicode fonts install on my system like DejaVu Sans:
![image](https://user-images.githubusercontent.com/7024137/69533421-17528e80-0f78-11ea-82a9-7999e0a65b67.png)
What do I miss here ?

**Comment by ema2159** [comment]
Could you try with Vanilla Emacs to see if the problem is Spacemacs?

**Comment by levindu** [comment]
Run the following code in the *scratch* buffer
```
(insert (all-the-icons-icon-for-file "foo.el"))
```

You should see the emacs icon inserted, and `C-u C-x =` on that char gives me:
```
             position: 49 of 18403 (0%), column: 0
            character:  (displayed as ) (codepoint 59686, #o164446, #xe926)
              charset: unicode (Unicode (ISO10646))
code point in charset: 0xE926
               syntax: w 	which means: word
             category: L:Left-to-right (strong)
             to input: type "C-x 8 RET e926"
          buffer code: #xEE #xA4 #xA6
            file code: #xEE #xA4 #xA6 (encoded by coding system utf-8)
              display: by this font (glyph code)
    xft:-PfEd-file-icons-normal-normal-normal-*-19-*-*-*-*-0-iso10646-1 (#x61)
```
Check your font here. Maybe after installing the fonts, you need to have a restart 
or desktop logout/login.

**Comment by fperies** [comment]
Thank you for your answers.

Here is my output:

![image](https://user-images.githubusercontent.com/7024137/69613685-44637780-1032-11ea-88c4-ce98647d5dc6.png)

So likely, the font is not correct.

For some reason, I'm not able to add all-file-icons font to the fontset created by Spacemacs.
If I try to add the font to the fontset manually as per suggestion from Troubleshooting section of project all-the-icons, my Emacs crashes !
I've opened an issue for this here:
https://github.com/domtronn/all-the-icons.el/issues/174

As suggested by @ema2159 , I have to give it a try with Vanilla Emacs on my system to be sure this trouble comes in with Spacemacs.

Any other suggestions are welcome !

**Comment by fperies** [comment]
Well, I've done a try with Vanilla Emacs and I have exactly the same behaviour:
![image](https://user-images.githubusercontent.com/7024137/69617377-6bbd4300-1038-11ea-85d4-c774fa04551d.png)

So maybe, my issue is not related to Spacemacs.
Help ! I'm totally confused 😕 !!

**Comment by fperies** [comment]
I've done some progress.

I've noticed that from Spacemacs, run M-x all-the-icons will create six .ttf files with actual XML content into ~/.local/shared/fonts folder.
So, I've cloned the project all-the-icons manually, copy the .ttf files (this time with binary content) into  the fonts directory and run the `fc-cache -f -v`command. And now, icons are back !!!!
![image](https://user-images.githubusercontent.com/7024137/69655358-a645d080-1076-11ea-990e-df5242903227.png)

But unfortunately, I still have the marker issue...

**Comment by levindu** [comment]
@fperies   If you're using Arch Linux, 

    sudo pacman -S ttf-hanazono

or Ubuntu, try:

    sudo apt install fonts-hanazono

**Comment by ema2159** [comment]
If I'm not wrong, he's using Red Hat. That may be what's making those fonts so hard to install.

**Comment by fperies** [comment]
Yes I use RedHat 7.
@levindu and @ema2159 
When I run command `(insert (make-string 1 #x23FA))` and `C-u C-x =` on the character inserted, I get the following output:
![image](https://user-images.githubusercontent.com/7024137/69724461-3d189880-111c-11ea-8463-011f5c01e430.png)
Could you please do the same and tell me what is the font you use ?
Thanks

**Comment by ema2159** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/17773218/69732647-a46d2300-10f1-11ea-8e49-f9e98d14d906.png)

**Comment by fperies** [comment]
Ok, thank you !
I've manually installed the font Google Noto Sans Symbols2 and now everything is fine:
![image](https://user-images.githubusercontent.com/7024137/69735944-d7cfa200-1131-11ea-8df9-645bc7047e03.png)

Thank you for your support !!

**Comment by ema2159** [comment]
Awesome! Glad to know you solved it! Just one thing, why there's a box around your icons? Do they look like that when you insert them on another buffer? Which theme are you using?

**Comment by fperies** [comment]
Regarding the box I don't know why it comes in with the tab.
But I don't have a box when icons are directly inserted:
![image](https://user-images.githubusercontent.com/7024137/69736523-f5e9d200-1132-11ea-8802-c3228134228e.png)
I use zenburn-theme which is largely used I guess.

**Comment by ema2159** [comment]
I had that problem before and it was a theming issue. Maybe try updating the theme or changing to one of the supported themes! However, those tabs are looking great! Thanks for using my package!

**Comment by goldfita** [comment]
I am also getting the 23FA text. I've installed all-the-icons-install-fonts and [Noto Sans](https://fonts.google.com/noto/specimen/Noto+Sans+Symbols+2) and restarted. In fact I upgraded to Win11 as well. Other icons appear to work.

Win11
Centaur Tabs 3.1
Emacs 28.1
