### ISSUE TITLE
Reversed left/right in centaur-tabs-select-separator-style

### ISSUE THREAD

**Issue by levindu** [ema2159/centaur-tabs#81]
Left/right are reversed in the following code:

https://github.com/ema2159/centaur-tabs/blob/0ae74715e36ce042ea8c2bf3491e5ed17c51158b/centaur-tabs.el#L1732-L1733

Is there any particular reason? Shouldn't it be:

```emacs-lisp
  (setq centaur-tabs-style-left (funcall (intern (format "powerline-%s-left" tab-style)) 'centaur-tabs-default nil centaur-tabs-height))
  (setq centaur-tabs-style-right (funcall (intern (format "powerline-%s-right" tab-style)) nil 'centaur-tabs-default centaur-tabs-height)))
```

I've had a strange wave separator view which leads me to the confusing lines.

**Comment by ema2159** [comment]
That comes from upstream. I'll have to give it a check!

**Comment by ema2159** [comment]
No. The code is correct.
For example, `centaur-tabs-style-left` refers to the left separator and `powerline-%s-right` refers to the direction in which that separator should be facing. In order for the left separator to be correct, it should be facing right in order to be facing towards it's respective tab.

**Comment by ema2159** [comment]
> I've had a strange wave separator view which leads me to the confusing lines.

However, it concerns me that you're telling me that you're having some problems with your separator's. Could you show me with a screenshot or something what's the problem?

**Comment by levindu** [comment]
This is using wave style in Spacemacs:

![orig](https://user-images.githubusercontent.com/18795/71566491-1bcc1300-2af3-11ea-9fa9-948c1f67fedc.png)

![modified](https://user-images.githubusercontent.com/18795/71566492-1d95d680-2af3-11ea-924f-8ee65bbd541d.png)

The modified one has a more natural view, whose wave shares the same background color with the editor window. While the original one has a somewhat ugly view with the active tab.
