### ISSUE TITLE
Set greyed out colour

### ISSUE THREAD

**Issue by tecosaur** [ema2159/centaur-tabs#82]
Hello. I just installed it and it's great! It may not be the "emacs way", but I love how it looks.
One minor issue, using _Doom Emacs_ with the `doom-vibrant` theme, the 'greyed out colour' is far too dark

![image](https://user-images.githubusercontent.com/20903656/71551723-e955e380-2a28-11ea-848a-367a54b75040.png)

Is there any way to change this?

Thanks in advance!

**Comment by ema2159** [comment]
Hi there! Remember, the only "Emacs way" there is is the one that works for you haha!

This bug is not from this plugin but from the `doom-themes` plugin. Luckily, I maintain that repo too so I'll fix it there. 

Thanks for using my plugin! As soon as I solve this I'll let you know!

**Comment by tecosaur** [comment]
Marvellous! Thanks for helping out :smiley:

**Comment by tecosaur** [comment]
Oh, by the way, `doom-one-light` could also use a similar fix (just to give you some more work :stuck_out_tongue_winking_eye:).

**Comment by ema2159** [comment]
@tecosaur Done! Hope you like it :smile:

**Comment by tecosaur** [comment]
Much better!
