### ISSUE TITLE
Performance issue re: centaur-tabs-buffer-groups

### ISSUE THREAD

**Issue by sorawee** [ema2159/centaur-tabs#83]
First of all, thanks for this amazing package :)

I notice a performance issue with `company` after enabling centaur tabs.  In particular, it used to be that interactions with `company` (like, show popup, select an item in the popup) takes only a few milliseconds. After `centaur-tabs` is enabled, each action takes several seconds! 

I tracked down the problem and found that my `centaur-tabs-buffer-groups` causes this problem. Each company action somehow triggers a recomputation of every buffer's `centaur-tabs-buffer-groups`, and since my `centaur-tabs-buffer-groups` is somewhat expensive, it causes the delay I mentioned above.

I fixed the above issue by caching the result in a buffer-local variable. But I think there's still something that is worth investigating/fixing:
1. Why does each company action triggers a recomputation of every buffer's `centaur-tabs-buffer-groups`? 
2. Could the documentation be improved by adding a warning regarding this performance problem? Having an example that shows how to cache the result would be really great too.

Thanks

**Comment by ema2159** [comment]
Hi! Perhaps you could show me the trace so I could see where is the function being called. Also I would like to see your caching solution so I could include it in the docs.

I'm aware of the performance issues there is, it's just that I haven't had the time to investigate and solve them properly.

**Comment by sorawee** [comment]
Here's the trace:

```
Debugger entered--entering a function:
* centaur-tabs-buffer-groups()
  #f(compiled-function (b) #<bytecode 0x456bc6f9>)(#<buffer test2.rkt>)
  mapcar(#f(compiled-function (b) #<bytecode 0x456bc6f9>) (#<buffer test2.rkt> #<buffer .spacemacs> #<buffer *spacemacs*> #<buffer *scratch*> #<buffer *Messages*> #<buffer *dotfile-test-results*> #<buffer *Warnings*> #<buffer *Backtrace*>))
  cl-mapcar(#f(compiled-function (b) #<bytecode 0x456bc6f9>) (#<buffer test2.rkt> #<buffer .spacemacs> #<buffer *spacemacs*> #<buffer *scratch*> #<buffer *Messages*> #<buffer *dotfile-test-results*> #<buffer *Warnings*> #<buffer *Backtrace*>))
  centaur-tabs-buffer-update-groups()
  run-hooks(buffer-list-update-hook)
  get-buffer-create(" *temp*-129724")
  generate-new-buffer(" *temp*")
  company-safe-substring("print" 0 26)
  company-fill-propertize(#("print" 0 4 (face (completions-common-part)) 4 5 (face (completions-first-difference))) nil 26 t " " " ")
  company--create-lines(0 10)
  company-pseudo-tooltip-show(5 0 0)
  company-pseudo-tooltip-show-at-point(31 4)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer test2.rkt> #<window 3 on test2.rkt> 76 31)
  apply(company-idle-begin (#<buffer test2.rkt> #<window 3 on test2.rkt> 76 31))
  timer-event-handler([t 24078 64996 541631 nil company-idle-begin (#<buffer test2.rkt> #<window 3 on test2.rkt> 76 31) nil 0])
```

Obviously, this is caused by how `company` creates a temporary buffer ` *temp*`.

Re: caching solution, mine is copied from `centaur-tabs-projectile-buffer-groups` :)

**Comment by ema2159** [comment]
Ok awesome, I think that I just need to add the *temp* buffer to the ignored buffers list in order to prevent `centaur-tabs-buffer-update-groups` from being executed, I'll get back at you when it's done.

**Comment by ema2159** [comment]
I did it but the function keeps being called. I'll try to check in the `centaur-tabs-buffer-update-groups` if the buffer belongs to the ignored buffers before recomputing all the tab groups. The only problem is that I'll be travelling for 15 days or so so I'll be unable to fix until I return.

**Comment by sorawee** [comment]
No rush!

**Comment by ema2159** [comment]
It seems that adding the *temp* buffer to the ignored list has improved the performance given that because it's not being added to any tab group, the cached groups are used instead. Still, I have to check this problem further.

**Comment by ema2159** [comment]
@sorawee, can you tell me if this keeps happening after the last commit?

**Comment by sorawee** [comment]
The problem persists for me, unfortunately. I define my own `centaur-tabs-buffer-groups` which I think will interfere with the default cached group?

**Comment by ema2159** [comment]
Is your centaur-tabs updated? Melpa hasn't updated it yet.
If it is updated, I'll have to check how to prevent the *temp buffer from even bein processed by centaur tabs. Your centaur-tabs-buffer-groups function shouldn't be interfering at all. Are you on Emacs 26 or 27? If you're on Emacs 27, I'd be interested on seeing how the native tabs handle this. That may give me some insights.

**Comment by sorawee** [comment]
It is. I pulled it directly from GitHub, and I confirmed that it has the following line:

```
     (string-prefix-p " *temp" name)
```

**Comment by sorawee** [comment]
I'm on Emacs 26.

**Comment by ema2159** [comment]
@sorawee there was an incredibly unnecessary hook that I merged some time ago without noticing. Now the problem shouldn't persist. Please test it and tell me if the error was fixed.

**Comment by sorawee** [comment]
Yep, it's fixed! Thanks so much for your help :)

**Comment by ema2159** [comment]
Nice! Thanks!
