### ISSUE TITLE
centaur-tabs-local-mode local to window

### ISSUE THREAD

**Issue by rcorrear** [ema2159/centaur-tabs#87]
Hi! First of all, very nice package, big fan of it! I've been wondering if it's possible to make centaur-tabs-local-mode (or a similar function) local to the window instead of the buffer?

My request comes from being a little annoyed at having the tabs visible in a popup window (a doom Emacs concept, just a smaller window at the bottom of the screen) for a REPL (cider, ielm) then toggling the tabs with (centaur-tabs-local-mode) and after some time switching to the same buffer but in the "main" window. Since variables keeping track of this are buffer local it means that the "big" window has no tabs as well when I switch to that buffer!

I hope you understood my issue, if not I can easily reproduce it and make a screencast. Thanks!

**Comment by ema2159** [comment]
Hi! Thanks for the kind words! I'd appreciate the screencast to be able to understand the error better!

**Comment by rcorrear** [comment]
Hi, sorry for the delay, forgot about this issue. I uploaded a very simple screencast here:

https://keybase.pub/rcorrear/centaur-tabs-local-mode.mov

It's a very simple description of what I'd like to achieve:

1. I open a new file, it's not relevant which file (but in this case I'm showing my config for centaur-tabs)/
2. I open an [IELM](http://wikemacs.org/wiki/IELM) "[popup](https://github.com/hlissner/doom-emacs/tree/develop/modules/ui/popup)" window (this is Doom Emacs' specific, it's windows that don't cover your whole screen and are easier to close).
3. For these kind of windows I don't want a tab bar, so I invoke `centaur-tabs-local-mode`, however:
4. For a little more serious work I do want to open the "full window" IELM, so I switch to that buffer in the main window.

Since the variables to disable the tab bar with `centaur-tabs-local-mode` are local to the buffer, switching to the IELM buffer in the main window hides the tab bar, which in this case is not exactly what I want.

All in all this is not a big issue, but I've been trying to polish the experience with tab usage and this is one of the last problems, if not the last one that I would like to fix.

**Comment by ema2159** [comment]
hmmm :thinking: Is there a way to detect when you're using a pop-up and when you're using the full window? To solve this, we should have a hook to detect when the popup is created and use something like a `(setq-local header-line-format nil)` for that popup only, but I'm not sure if that would enable it also in the IELM buffer. I think I'll ask Henrik, he can explain me  little bit more in detail how the API works.

**Comment by folke** [comment]
You can use `+popup-window-p` to check whether the active window is a popup window.

I use the code below to (de)activate centaur tabs depending on whether the current buffer is in a popup window or not:

```elisp
(after! centaur-tabs
  (+popup-window-p) ; needed to prevent recursive auto-loading of popup

  ;; Automatically turn off tabs in popups
  (defun +fl/hide-tabs-in-popup ()
    (if (+popup-window-p)
        (centaur-tabs-local-mode)
      (centaur-tabs-local-mode 0)))
  (add-hook! 'buffer-list-update-hook '+fl/hide-tabs-in-popup))
```

Hooking into `buffer-list-update-hook` is a bit of a hack, but it works. This hook is ran whenever you switch to another buffer.

**Comment by folke** [comment]
@rcorrear to have this enabled only for IELM, simply hook the `+fl/hide-tabs-in-popup` to the ielm major mode hook.

**Comment by rcorrear** [comment]
Thanks @folke, that makes sense!
