### ISSUE TITLE
centaur-tabs-forward-tab behavior

### ISSUE THREAD

**Issue by djangoliv** [ema2159/centaur-tabs#9]
IMHO !!
I think centaur-tabs-forward-tab and centaur-tabs-backward-tab should stay in the same tab-set.
it is disturbing to change the group of tabs without using centaur-tabs-forward-group.

Regards

**Comment by ema2159** [comment]
I might have to disagree. Me personally as a user if I see that I'm on the last tab of a group I know that if I do a forward/backward I'll change group and that's something I tend to use a lot. I don't know if i might want to change that.
Regards

**Comment by ema2159** [comment]
A solution I might offer though would be to set a custom `centaur-tabs-cycle` that if it's t, it wold cycle through the tabs, I don't know if that's what you have in mind

**Comment by ema2159** [comment]
Luckily, it's a feature that's already implemented. I didn't knew jaja! You just have to do a simple `(setq centaur-tabs-cycle-scope 'tabs)`. I'll add it to the documentation.
