### ISSUE TITLE
Terminal Compatibility

### ISSUE THREAD

**Issue by pawalt** [ema2159/centaur-tabs#90]
Hi! I'm a big fan of this package, and it looks fantastic in my GUI in a way other tab plugins don't. I'm wondering if there are any plans to add rudimentary terminal support? I'd love to run the same editor in the terminal and GUI, and tabs are a pretty core part of how I work.

Thanks for the help!

**Comment by ema2159** [comment]
Hi! I haven't experimented much with term Emacs, but you're right, it would be a great addition to make centaur-tabs work for in Emacs TUI. I currently am a little bit time-limited but I'll try to dig into it soon.

**Comment by pawalt** [comment]
Gotcha thanks! I'm no elisp expert by any means but if you point me to right place, I can take a crack at TUI compatibility.

**Comment by ema2159** [comment]
Sorry for the late response! This quarantine stuff really makes everything more difficult.
I'm not sure what exactly causes the tabs not to work in the terminal, however, there are several things I know need to be disabled in the terminal like for example the icons, close buttons and I'm not sure if also the line that highlights the currently selected tab needs to be disabled also. One thing that doesn't work that should work are tab motions.  All of them call the `centaur-tabs-cycle` function with different parameters so maybe that's a good place to start.

**Comment by rorokimdim** [comment]
@ema2159  thanks for the nice package.

I'm quite satisfied with the way it works in the terminal. I've only tried it on Mac with iterm2 though.

The only thing that would have been nice if I could switch tabs with click of a mouse -- neotree/ranger and mouse clicks work in my terminal (I use iterm2 on mac)

Sometimes it's convenient to use the mouse to jump around quickly. But binding keyboard shortcuts to something like the following function works well enough for how I work.

`(defun my-centaur-tabs-jump-to (n)
  (centaur-tabs-select-beg-tab)
  (dotimes (i n)
    (centaur-tabs-forward)))`

**Comment by laishulu** [comment]
Is this expected currently?
The bar is totally blank in my TUI Emacs.
![图片](https://user-images.githubusercontent.com/1224321/82109266-2ec04680-9767-11ea-9168-3c9123ee3edf.png)

**Comment by ema2159** [comment]
I'm not quite sure, I'd have to check. I've been quite away from TUI Emacs since in my job I'm forced to use a Windows environment.

**Comment by laishulu** [comment]
Any progress?
Do you need me to provide a terminal envrionment for you for testing?

**Comment by laishulu** [comment]
Figured out:
With the following codes, it will works in TUI
```
  (setq centaur-tabs-set-bar nil)
```

**Comment by pawalt** [comment]
Ah yep that made it work for me as well

**Comment by ema2159** [comment]
Was it that easy? Also I think icons have to be disabled. I'll try to deactivate icons and the bar by default on TUI Emacs then

**Comment by laishulu** [comment]
for `centaur-tabs-set-bar`, I have tested, anyone of `nil` `'under` and `'over` works,
the only value that does not work is `'left`.

**Comment by laishulu** [comment]
@ema2159 Any progress?

**Comment by ema2159** [comment]
Note quite yet! I hope to be able to do it in the weekend.

**Comment by ssiyad** [comment]
Hyped for this!

**Comment by ema2159** [comment]
I turns out it was much easier than expected. I initially thought the cycling function didn't work because I had it binded to `C-<previous>` and `C-<next>` which for some odd reason don't work in TUI. The change was really simple, I just turned off some options that simply don't work in TUI Emacs, however there may be more things to turn off, so please let me know if you find some.
