### ISSUE TITLE
Customizing faces breaks stuff and unknown background color?

### ISSUE THREAD

**Issue by ChrisMGeo** [ema2159/centaur-tabs#91]
Hi, I'm a Spacemacs user and am just getting started with (Spac)emacs. The plugin looks great and functions well, but when I customize faces like the colours of the tabs and restart emacs, I get some errors and have to revert to using the stock emacs to edit the `.spacemacs` file to find the line
`'(centaur-tabs-mode t nil (centaur-tabs))` in `custom-set-variables`, which somehow causes the error, so removing it works, but it still happens whenever I customize the faces. On the topic of colours, I also wanted to ask how to change the following colour: 
![centaurtabs](https://user-images.githubusercontent.com/44679968/78420131-54abe480-761a-11ea-9923-fdc2cf7144d9.png)

**Comment by ema2159** [comment]
Hello! Sorry for the late response. Regarding the first issue, I'll need to look into it, but regarding that color you point, you either do `(centaur-tabs-headline-match)` and it will take the unselected tabs color, or you can directly configure the header-line face.

**Comment by ChrisMGeo** [comment]
@ema2159 Thanks for the response, and the answer for the second issue. Should I close this issue now?

**Comment by ema2159** [comment]
It depends. Is the first issue still happening?

**Comment by ema2159** [comment]
Is this issue solved?
