### ISSUE TITLE
org-agenda makes ct open every visited file in a tab

### ISSUE THREAD

**Issue by peterhoeg** [ema2159/centaur-tabs#93]
What happens is this:

1. Open a single `.org` file
2. Run `org-agenda`
3. Wait for `org` to do its thing
4. I am now switched to the `* Org Agenda*` buffer in the `Emacs` buffer group (I haven't changed the rules yet)
5. Switching back to my initial `.org` file reveals hundreds of open tabs - one for each `.org` file that `org-agenda` has been going through.

Ideally, it would be great to have ct *not* create a tab for each file - only those that I actually open.

**Comment by tnira** [comment]
It is normal for org-agenda to open the buffer of the file to be displayed on the agenda when it is executed.
I think centaur-tabs is just faithfully showing it as a tab.
I think it would be better to set the `setq org-agenda-files` and limit the target files for agenda display, but isn't that what you're saying?

**Comment by peterhoeg** [comment]
>   It is normal for org-agenda to open the buffer of the file to be displayed
>   on the agenda when it is executed.

Be that as it may, that doesn't change the fact that it doesn't show up in the buffer list as an active buffer until I specifically visit a file and yet still shows a tab for it.

If I execute +ivy/switch-workspace-buffer, I still only see the buffers that were manually visited although ivy-switch-buffer shows me everything (231 when I just tried).

>   I think it would be better to set the setq org-agenda-files and limit the
>   target files for agenda display, but isn't that what you're saying?

I need all those .org files taken into account for the agenda. But I still don't want them open as tabs.

And without ct, this isn't an issue as triggering the agenda doesn't pollute my buffer list.

**Comment by tnira** [comment]
> that doesn't change the fact that it doesn't show up in the buffer list as an active buffer until I specifically visit a file and yet still shows a tab for it.
At least, I couldn't reproduce such a phenomenon in my environment.

**Comment by peterhoeg** [comment]
I have just realizesd that `org-refile` also makes ct create a tab for every possible refile target. So there is definitely something strange about how ct determines if/when a tab should be created.

**Comment by peterhoeg** [comment]
> And without ct, this isn't an issue as triggering the agenda doesn't pollute my buffer list.

Turns out it isn't a ct thing as such.

**Comment by Xunius** [comment]
@peterhoeg so if it is not ct, what's causing this behavior? Could you share your solution? I'm having the same problem that `org-agenda` opens all my org files as tabs.

**Comment by peterhoeg** [comment]
>   @peterhoeg so if it is not ct, what's causing this behavior? Could you

org-mode will open a buffer for each .org file when building the agenda and ct then simply shows you a tab for each open buffer.

What ct *could* be made to do is to only show a tab for every buffer visited interactively as opposed to programmatically but it doesn't support that.

I simply switched to the built-in tab-bar-mode in emacs 27 for 2 reasons:

1. it gives me tabs per frame instead of tabs per window (which is what I want - the built-in mode does however also support tab-line-mode which is tabs per window), and
2. one less external dependency

Ct is definitely prettier but the built-in mode supports my workflow better.

**Comment by Xunius** [comment]
@peterhoeg Thanks for the info. Are you referring to this tabar (https://github.com/dholm/tabbar)? I just installed it and removed ct, however `org-agent` still opens all tabs. What I'm missing?

**Comment by peterhoeg** [comment]
>   @peterhoeg Thanks for the info. Are you referring to this tabar
>   (https://github.com/dholm/tabbar)?

No, Emacs 27 has tab-bar-mode built-in.
