### ISSUE TITLE
Feature request: support ace-jump or avy to jump different tabs

### ISSUE THREAD

**Issue by lyjdwh** [ema2159/centaur-tabs#95]
Hi, thank you for this package! I've really enjoyed it.

Here is the situation. When the tab we need to go is far from the current tab, `centaur-tabs-forward/backward` maybe not so efficient, maybe the way `ace-jump` or `avy` uses is more efficient!

**Comment by ema2159** [comment]
Nice idea! I think awesome-tab (the package in which this plugin is based on) has that function. I'll try to check how it's implemented and then use it for centaur.
